// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ConstituenciesDeleteReader is a Reader for the ConstituenciesDelete structure.
type ConstituenciesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConstituenciesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewConstituenciesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /CRM/Constituencies/{constituencyId}] Constituencies_Delete", response, response.Code())
	}
}

// NewConstituenciesDeleteNoContent creates a ConstituenciesDeleteNoContent with default headers values
func NewConstituenciesDeleteNoContent() *ConstituenciesDeleteNoContent {
	return &ConstituenciesDeleteNoContent{}
}

/*
ConstituenciesDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type ConstituenciesDeleteNoContent struct {
}

// IsSuccess returns true when this constituencies delete no content response has a 2xx status code
func (o *ConstituenciesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this constituencies delete no content response has a 3xx status code
func (o *ConstituenciesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this constituencies delete no content response has a 4xx status code
func (o *ConstituenciesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this constituencies delete no content response has a 5xx status code
func (o *ConstituenciesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this constituencies delete no content response a status code equal to that given
func (o *ConstituenciesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the constituencies delete no content response
func (o *ConstituenciesDeleteNoContent) Code() int {
	return 204
}

func (o *ConstituenciesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /CRM/Constituencies/{constituencyId}][%d] constituenciesDeleteNoContent ", 204)
}

func (o *ConstituenciesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /CRM/Constituencies/{constituencyId}][%d] constituenciesDeleteNoContent ", 204)
}

func (o *ConstituenciesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
