// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPhilanthropyDeleteParams creates a new PhilanthropyDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPhilanthropyDeleteParams() *PhilanthropyDeleteParams {
	return &PhilanthropyDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPhilanthropyDeleteParamsWithTimeout creates a new PhilanthropyDeleteParams object
// with the ability to set a timeout on a request.
func NewPhilanthropyDeleteParamsWithTimeout(timeout time.Duration) *PhilanthropyDeleteParams {
	return &PhilanthropyDeleteParams{
		timeout: timeout,
	}
}

// NewPhilanthropyDeleteParamsWithContext creates a new PhilanthropyDeleteParams object
// with the ability to set a context for a request.
func NewPhilanthropyDeleteParamsWithContext(ctx context.Context) *PhilanthropyDeleteParams {
	return &PhilanthropyDeleteParams{
		Context: ctx,
	}
}

// NewPhilanthropyDeleteParamsWithHTTPClient creates a new PhilanthropyDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPhilanthropyDeleteParamsWithHTTPClient(client *http.Client) *PhilanthropyDeleteParams {
	return &PhilanthropyDeleteParams{
		HTTPClient: client,
	}
}

/*
PhilanthropyDeleteParams contains all the parameters to send to the API endpoint

	for the philanthropy delete operation.

	Typically these are written to a http.Request.
*/
type PhilanthropyDeleteParams struct {

	// PhilanthropyEntryID.
	PhilanthropyEntryID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the philanthropy delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PhilanthropyDeleteParams) WithDefaults() *PhilanthropyDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the philanthropy delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PhilanthropyDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the philanthropy delete params
func (o *PhilanthropyDeleteParams) WithTimeout(timeout time.Duration) *PhilanthropyDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the philanthropy delete params
func (o *PhilanthropyDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the philanthropy delete params
func (o *PhilanthropyDeleteParams) WithContext(ctx context.Context) *PhilanthropyDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the philanthropy delete params
func (o *PhilanthropyDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the philanthropy delete params
func (o *PhilanthropyDeleteParams) WithHTTPClient(client *http.Client) *PhilanthropyDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the philanthropy delete params
func (o *PhilanthropyDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPhilanthropyEntryID adds the philanthropyEntryID to the philanthropy delete params
func (o *PhilanthropyDeleteParams) WithPhilanthropyEntryID(philanthropyEntryID string) *PhilanthropyDeleteParams {
	o.SetPhilanthropyEntryID(philanthropyEntryID)
	return o
}

// SetPhilanthropyEntryID adds the philanthropyEntryId to the philanthropy delete params
func (o *PhilanthropyDeleteParams) SetPhilanthropyEntryID(philanthropyEntryID string) {
	o.PhilanthropyEntryID = philanthropyEntryID
}

// WriteToRequest writes these params to a swagger request
func (o *PhilanthropyDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param philanthropyEntryId
	if err := r.SetPathParam("philanthropyEntryId", o.PhilanthropyEntryID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
