// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPhoneIndicatorsDeleteParams creates a new PhoneIndicatorsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPhoneIndicatorsDeleteParams() *PhoneIndicatorsDeleteParams {
	return &PhoneIndicatorsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPhoneIndicatorsDeleteParamsWithTimeout creates a new PhoneIndicatorsDeleteParams object
// with the ability to set a timeout on a request.
func NewPhoneIndicatorsDeleteParamsWithTimeout(timeout time.Duration) *PhoneIndicatorsDeleteParams {
	return &PhoneIndicatorsDeleteParams{
		timeout: timeout,
	}
}

// NewPhoneIndicatorsDeleteParamsWithContext creates a new PhoneIndicatorsDeleteParams object
// with the ability to set a context for a request.
func NewPhoneIndicatorsDeleteParamsWithContext(ctx context.Context) *PhoneIndicatorsDeleteParams {
	return &PhoneIndicatorsDeleteParams{
		Context: ctx,
	}
}

// NewPhoneIndicatorsDeleteParamsWithHTTPClient creates a new PhoneIndicatorsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewPhoneIndicatorsDeleteParamsWithHTTPClient(client *http.Client) *PhoneIndicatorsDeleteParams {
	return &PhoneIndicatorsDeleteParams{
		HTTPClient: client,
	}
}

/*
PhoneIndicatorsDeleteParams contains all the parameters to send to the API endpoint

	for the phone indicators delete operation.

	Typically these are written to a http.Request.
*/
type PhoneIndicatorsDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the phone indicators delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PhoneIndicatorsDeleteParams) WithDefaults() *PhoneIndicatorsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the phone indicators delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PhoneIndicatorsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) WithTimeout(timeout time.Duration) *PhoneIndicatorsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) WithContext(ctx context.Context) *PhoneIndicatorsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) WithHTTPClient(client *http.Client) *PhoneIndicatorsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) WithID(id string) *PhoneIndicatorsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the phone indicators delete params
func (o *PhoneIndicatorsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PhoneIndicatorsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
