// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PriceTypeCategoriesDeleteReader is a Reader for the PriceTypeCategoriesDelete structure.
type PriceTypeCategoriesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PriceTypeCategoriesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPriceTypeCategoriesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPriceTypeCategoriesDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPriceTypeCategoriesDeleteNoContent creates a PriceTypeCategoriesDeleteNoContent with default headers values
func NewPriceTypeCategoriesDeleteNoContent() *PriceTypeCategoriesDeleteNoContent {
	return &PriceTypeCategoriesDeleteNoContent{}
}

/*
PriceTypeCategoriesDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type PriceTypeCategoriesDeleteNoContent struct {
}

// IsSuccess returns true when this price type categories delete no content response has a 2xx status code
func (o *PriceTypeCategoriesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this price type categories delete no content response has a 3xx status code
func (o *PriceTypeCategoriesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this price type categories delete no content response has a 4xx status code
func (o *PriceTypeCategoriesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this price type categories delete no content response has a 5xx status code
func (o *PriceTypeCategoriesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this price type categories delete no content response a status code equal to that given
func (o *PriceTypeCategoriesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the price type categories delete no content response
func (o *PriceTypeCategoriesDeleteNoContent) Code() int {
	return 204
}

func (o *PriceTypeCategoriesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ReferenceData/PriceTypeCategories/{id}][%d] priceTypeCategoriesDeleteNoContent", 204)
}

func (o *PriceTypeCategoriesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /ReferenceData/PriceTypeCategories/{id}][%d] priceTypeCategoriesDeleteNoContent", 204)
}

func (o *PriceTypeCategoriesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPriceTypeCategoriesDeleteDefault creates a PriceTypeCategoriesDeleteDefault with default headers values
func NewPriceTypeCategoriesDeleteDefault(code int) *PriceTypeCategoriesDeleteDefault {
	return &PriceTypeCategoriesDeleteDefault{
		_statusCode: code,
	}
}

/*
PriceTypeCategoriesDeleteDefault describes a response with status code -1, with default header values.

Error
*/
type PriceTypeCategoriesDeleteDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this price type categories delete default response has a 2xx status code
func (o *PriceTypeCategoriesDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this price type categories delete default response has a 3xx status code
func (o *PriceTypeCategoriesDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this price type categories delete default response has a 4xx status code
func (o *PriceTypeCategoriesDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this price type categories delete default response has a 5xx status code
func (o *PriceTypeCategoriesDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this price type categories delete default response a status code equal to that given
func (o *PriceTypeCategoriesDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the price type categories delete default response
func (o *PriceTypeCategoriesDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PriceTypeCategoriesDeleteDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /ReferenceData/PriceTypeCategories/{id}][%d] PriceTypeCategories_Delete default %s", o._statusCode, payload)
}

func (o *PriceTypeCategoriesDeleteDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /ReferenceData/PriceTypeCategories/{id}][%d] PriceTypeCategories_Delete default %s", o._statusCode, payload)
}

func (o *PriceTypeCategoriesDeleteDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PriceTypeCategoriesDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
