// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PricingRulesDeleteReader is a Reader for the PricingRulesDelete structure.
type PricingRulesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingRulesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewPricingRulesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPricingRulesDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPricingRulesDeleteNoContent creates a PricingRulesDeleteNoContent with default headers values
func NewPricingRulesDeleteNoContent() *PricingRulesDeleteNoContent {
	return &PricingRulesDeleteNoContent{}
}

/*
PricingRulesDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type PricingRulesDeleteNoContent struct {
}

// IsSuccess returns true when this pricing rules delete no content response has a 2xx status code
func (o *PricingRulesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing rules delete no content response has a 3xx status code
func (o *PricingRulesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing rules delete no content response has a 4xx status code
func (o *PricingRulesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing rules delete no content response has a 5xx status code
func (o *PricingRulesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing rules delete no content response a status code equal to that given
func (o *PricingRulesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the pricing rules delete no content response
func (o *PricingRulesDeleteNoContent) Code() int {
	return 204
}

func (o *PricingRulesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /TXN/PricingRules/{pricingRuleId}][%d] pricingRulesDeleteNoContent", 204)
}

func (o *PricingRulesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /TXN/PricingRules/{pricingRuleId}][%d] pricingRulesDeleteNoContent", 204)
}

func (o *PricingRulesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPricingRulesDeleteDefault creates a PricingRulesDeleteDefault with default headers values
func NewPricingRulesDeleteDefault(code int) *PricingRulesDeleteDefault {
	return &PricingRulesDeleteDefault{
		_statusCode: code,
	}
}

/*
PricingRulesDeleteDefault describes a response with status code -1, with default header values.

Error
*/
type PricingRulesDeleteDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this pricing rules delete default response has a 2xx status code
func (o *PricingRulesDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this pricing rules delete default response has a 3xx status code
func (o *PricingRulesDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this pricing rules delete default response has a 4xx status code
func (o *PricingRulesDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this pricing rules delete default response has a 5xx status code
func (o *PricingRulesDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this pricing rules delete default response a status code equal to that given
func (o *PricingRulesDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the pricing rules delete default response
func (o *PricingRulesDeleteDefault) Code() int {
	return o._statusCode
}

func (o *PricingRulesDeleteDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /TXN/PricingRules/{pricingRuleId}][%d] PricingRules_Delete default %s", o._statusCode, payload)
}

func (o *PricingRulesDeleteDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /TXN/PricingRules/{pricingRuleId}][%d] PricingRules_Delete default %s", o._statusCode, payload)
}

func (o *PricingRulesDeleteDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PricingRulesDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
