// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewProductionSeasonMembershipOrganizationsDeleteParams creates a new ProductionSeasonMembershipOrganizationsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewProductionSeasonMembershipOrganizationsDeleteParams() *ProductionSeasonMembershipOrganizationsDeleteParams {
	return &ProductionSeasonMembershipOrganizationsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewProductionSeasonMembershipOrganizationsDeleteParamsWithTimeout creates a new ProductionSeasonMembershipOrganizationsDeleteParams object
// with the ability to set a timeout on a request.
func NewProductionSeasonMembershipOrganizationsDeleteParamsWithTimeout(timeout time.Duration) *ProductionSeasonMembershipOrganizationsDeleteParams {
	return &ProductionSeasonMembershipOrganizationsDeleteParams{
		timeout: timeout,
	}
}

// NewProductionSeasonMembershipOrganizationsDeleteParamsWithContext creates a new ProductionSeasonMembershipOrganizationsDeleteParams object
// with the ability to set a context for a request.
func NewProductionSeasonMembershipOrganizationsDeleteParamsWithContext(ctx context.Context) *ProductionSeasonMembershipOrganizationsDeleteParams {
	return &ProductionSeasonMembershipOrganizationsDeleteParams{
		Context: ctx,
	}
}

// NewProductionSeasonMembershipOrganizationsDeleteParamsWithHTTPClient creates a new ProductionSeasonMembershipOrganizationsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewProductionSeasonMembershipOrganizationsDeleteParamsWithHTTPClient(client *http.Client) *ProductionSeasonMembershipOrganizationsDeleteParams {
	return &ProductionSeasonMembershipOrganizationsDeleteParams{
		HTTPClient: client,
	}
}

/*
ProductionSeasonMembershipOrganizationsDeleteParams contains all the parameters to send to the API endpoint

	for the production season membership organizations delete operation.

	Typically these are written to a http.Request.
*/
type ProductionSeasonMembershipOrganizationsDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the production season membership organizations delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WithDefaults() *ProductionSeasonMembershipOrganizationsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the production season membership organizations delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WithTimeout(timeout time.Duration) *ProductionSeasonMembershipOrganizationsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WithContext(ctx context.Context) *ProductionSeasonMembershipOrganizationsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WithHTTPClient(client *http.Client) *ProductionSeasonMembershipOrganizationsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WithID(id string) *ProductionSeasonMembershipOrganizationsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the production season membership organizations delete params
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ProductionSeasonMembershipOrganizationsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
