// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryElementsDeleteParams creates a new QueryElementsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryElementsDeleteParams() *QueryElementsDeleteParams {
	return &QueryElementsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryElementsDeleteParamsWithTimeout creates a new QueryElementsDeleteParams object
// with the ability to set a timeout on a request.
func NewQueryElementsDeleteParamsWithTimeout(timeout time.Duration) *QueryElementsDeleteParams {
	return &QueryElementsDeleteParams{
		timeout: timeout,
	}
}

// NewQueryElementsDeleteParamsWithContext creates a new QueryElementsDeleteParams object
// with the ability to set a context for a request.
func NewQueryElementsDeleteParamsWithContext(ctx context.Context) *QueryElementsDeleteParams {
	return &QueryElementsDeleteParams{
		Context: ctx,
	}
}

// NewQueryElementsDeleteParamsWithHTTPClient creates a new QueryElementsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryElementsDeleteParamsWithHTTPClient(client *http.Client) *QueryElementsDeleteParams {
	return &QueryElementsDeleteParams{
		HTTPClient: client,
	}
}

/*
QueryElementsDeleteParams contains all the parameters to send to the API endpoint

	for the query elements delete operation.

	Typically these are written to a http.Request.
*/
type QueryElementsDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query elements delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryElementsDeleteParams) WithDefaults() *QueryElementsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query elements delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryElementsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query elements delete params
func (o *QueryElementsDeleteParams) WithTimeout(timeout time.Duration) *QueryElementsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query elements delete params
func (o *QueryElementsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query elements delete params
func (o *QueryElementsDeleteParams) WithContext(ctx context.Context) *QueryElementsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query elements delete params
func (o *QueryElementsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query elements delete params
func (o *QueryElementsDeleteParams) WithHTTPClient(client *http.Client) *QueryElementsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query elements delete params
func (o *QueryElementsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the query elements delete params
func (o *QueryElementsDeleteParams) WithID(id string) *QueryElementsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the query elements delete params
func (o *QueryElementsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *QueryElementsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
