// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ReceiptSettingsDeleteReader is a Reader for the ReceiptSettingsDelete structure.
type ReceiptSettingsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReceiptSettingsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewReceiptSettingsDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /ReferenceData/ReceiptSettings/{id}] ReceiptSettings_Delete", response, response.Code())
	}
}

// NewReceiptSettingsDeleteNoContent creates a ReceiptSettingsDeleteNoContent with default headers values
func NewReceiptSettingsDeleteNoContent() *ReceiptSettingsDeleteNoContent {
	return &ReceiptSettingsDeleteNoContent{}
}

/*
ReceiptSettingsDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type ReceiptSettingsDeleteNoContent struct {
}

// IsSuccess returns true when this receipt settings delete no content response has a 2xx status code
func (o *ReceiptSettingsDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this receipt settings delete no content response has a 3xx status code
func (o *ReceiptSettingsDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this receipt settings delete no content response has a 4xx status code
func (o *ReceiptSettingsDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this receipt settings delete no content response has a 5xx status code
func (o *ReceiptSettingsDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this receipt settings delete no content response a status code equal to that given
func (o *ReceiptSettingsDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the receipt settings delete no content response
func (o *ReceiptSettingsDeleteNoContent) Code() int {
	return 204
}

func (o *ReceiptSettingsDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ReferenceData/ReceiptSettings/{id}][%d] receiptSettingsDeleteNoContent ", 204)
}

func (o *ReceiptSettingsDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /ReferenceData/ReceiptSettings/{id}][%d] receiptSettingsDeleteNoContent ", 204)
}

func (o *ReceiptSettingsDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
