// Code generated by go-swagger; DO NOT EDIT.

package d_e_l_e_t_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWebContentTypesDeleteParams creates a new WebContentTypesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWebContentTypesDeleteParams() *WebContentTypesDeleteParams {
	return &WebContentTypesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWebContentTypesDeleteParamsWithTimeout creates a new WebContentTypesDeleteParams object
// with the ability to set a timeout on a request.
func NewWebContentTypesDeleteParamsWithTimeout(timeout time.Duration) *WebContentTypesDeleteParams {
	return &WebContentTypesDeleteParams{
		timeout: timeout,
	}
}

// NewWebContentTypesDeleteParamsWithContext creates a new WebContentTypesDeleteParams object
// with the ability to set a context for a request.
func NewWebContentTypesDeleteParamsWithContext(ctx context.Context) *WebContentTypesDeleteParams {
	return &WebContentTypesDeleteParams{
		Context: ctx,
	}
}

// NewWebContentTypesDeleteParamsWithHTTPClient creates a new WebContentTypesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewWebContentTypesDeleteParamsWithHTTPClient(client *http.Client) *WebContentTypesDeleteParams {
	return &WebContentTypesDeleteParams{
		HTTPClient: client,
	}
}

/*
WebContentTypesDeleteParams contains all the parameters to send to the API endpoint

	for the web content types delete operation.

	Typically these are written to a http.Request.
*/
type WebContentTypesDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the web content types delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebContentTypesDeleteParams) WithDefaults() *WebContentTypesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the web content types delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WebContentTypesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the web content types delete params
func (o *WebContentTypesDeleteParams) WithTimeout(timeout time.Duration) *WebContentTypesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the web content types delete params
func (o *WebContentTypesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the web content types delete params
func (o *WebContentTypesDeleteParams) WithContext(ctx context.Context) *WebContentTypesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the web content types delete params
func (o *WebContentTypesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the web content types delete params
func (o *WebContentTypesDeleteParams) WithHTTPClient(client *http.Client) *WebContentTypesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the web content types delete params
func (o *WebContentTypesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the web content types delete params
func (o *WebContentTypesDeleteParams) WithID(id string) *WebContentTypesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the web content types delete params
func (o *WebContentTypesDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *WebContentTypesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
