// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ActivityTypesGetAllReader is a Reader for the ActivityTypesGetAll structure.
type ActivityTypesGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivityTypesGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewActivityTypesGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewActivityTypesGetAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActivityTypesGetAllOK creates a ActivityTypesGetAllOK with default headers values
func NewActivityTypesGetAllOK() *ActivityTypesGetAllOK {
	return &ActivityTypesGetAllOK{}
}

/*
ActivityTypesGetAllOK describes a response with status code 200, with default header values.

OK
*/
type ActivityTypesGetAllOK struct {
	Payload []*models.ActivityType
}

// IsSuccess returns true when this activity types get all o k response has a 2xx status code
func (o *ActivityTypesGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this activity types get all o k response has a 3xx status code
func (o *ActivityTypesGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this activity types get all o k response has a 4xx status code
func (o *ActivityTypesGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this activity types get all o k response has a 5xx status code
func (o *ActivityTypesGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this activity types get all o k response a status code equal to that given
func (o *ActivityTypesGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the activity types get all o k response
func (o *ActivityTypesGetAllOK) Code() int {
	return 200
}

func (o *ActivityTypesGetAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ActivityTypes][%d] activityTypesGetAllOK %s", 200, payload)
}

func (o *ActivityTypesGetAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ActivityTypes][%d] activityTypesGetAllOK %s", 200, payload)
}

func (o *ActivityTypesGetAllOK) GetPayload() []*models.ActivityType {
	return o.Payload
}

func (o *ActivityTypesGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivityTypesGetAllDefault creates a ActivityTypesGetAllDefault with default headers values
func NewActivityTypesGetAllDefault(code int) *ActivityTypesGetAllDefault {
	return &ActivityTypesGetAllDefault{
		_statusCode: code,
	}
}

/*
ActivityTypesGetAllDefault describes a response with status code -1, with default header values.

Error
*/
type ActivityTypesGetAllDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this activity types get all default response has a 2xx status code
func (o *ActivityTypesGetAllDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this activity types get all default response has a 3xx status code
func (o *ActivityTypesGetAllDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this activity types get all default response has a 4xx status code
func (o *ActivityTypesGetAllDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this activity types get all default response has a 5xx status code
func (o *ActivityTypesGetAllDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this activity types get all default response a status code equal to that given
func (o *ActivityTypesGetAllDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the activity types get all default response
func (o *ActivityTypesGetAllDefault) Code() int {
	return o._statusCode
}

func (o *ActivityTypesGetAllDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ActivityTypes][%d] ActivityTypes_GetAll default %s", o._statusCode, payload)
}

func (o *ActivityTypesGetAllDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ActivityTypes][%d] ActivityTypes_GetAll default %s", o._statusCode, payload)
}

func (o *ActivityTypesGetAllDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ActivityTypesGetAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
