// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// AddressesGetAllReader is a Reader for the AddressesGetAll structure.
type AddressesGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressesGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressesGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /CRM/Addresses] Addresses_GetAll", response, response.Code())
	}
}

// NewAddressesGetAllOK creates a AddressesGetAllOK with default headers values
func NewAddressesGetAllOK() *AddressesGetAllOK {
	return &AddressesGetAllOK{}
}

/*
AddressesGetAllOK describes a response with status code 200, with default header values.

OK
*/
type AddressesGetAllOK struct {
	Payload []*models.Address
}

// IsSuccess returns true when this addresses get all o k response has a 2xx status code
func (o *AddressesGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this addresses get all o k response has a 3xx status code
func (o *AddressesGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this addresses get all o k response has a 4xx status code
func (o *AddressesGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this addresses get all o k response has a 5xx status code
func (o *AddressesGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this addresses get all o k response a status code equal to that given
func (o *AddressesGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the addresses get all o k response
func (o *AddressesGetAllOK) Code() int {
	return 200
}

func (o *AddressesGetAllOK) Error() string {
	return fmt.Sprintf("[GET /CRM/Addresses][%d] addressesGetAllOK  %+v", 200, o.Payload)
}

func (o *AddressesGetAllOK) String() string {
	return fmt.Sprintf("[GET /CRM/Addresses][%d] addressesGetAllOK  %+v", 200, o.Payload)
}

func (o *AddressesGetAllOK) GetPayload() []*models.Address {
	return o.Payload
}

func (o *AddressesGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
