// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ArtistsGetAllReader is a Reader for the ArtistsGetAll structure.
type ArtistsGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ArtistsGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewArtistsGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewArtistsGetAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewArtistsGetAllOK creates a ArtistsGetAllOK with default headers values
func NewArtistsGetAllOK() *ArtistsGetAllOK {
	return &ArtistsGetAllOK{}
}

/*
ArtistsGetAllOK describes a response with status code 200, with default header values.

OK
*/
type ArtistsGetAllOK struct {
	Payload []*models.Artist
}

// IsSuccess returns true when this artists get all o k response has a 2xx status code
func (o *ArtistsGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this artists get all o k response has a 3xx status code
func (o *ArtistsGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this artists get all o k response has a 4xx status code
func (o *ArtistsGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this artists get all o k response has a 5xx status code
func (o *ArtistsGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this artists get all o k response a status code equal to that given
func (o *ArtistsGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the artists get all o k response
func (o *ArtistsGetAllOK) Code() int {
	return 200
}

func (o *ArtistsGetAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/Artists][%d] artistsGetAllOK %s", 200, payload)
}

func (o *ArtistsGetAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/Artists][%d] artistsGetAllOK %s", 200, payload)
}

func (o *ArtistsGetAllOK) GetPayload() []*models.Artist {
	return o.Payload
}

func (o *ArtistsGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewArtistsGetAllDefault creates a ArtistsGetAllDefault with default headers values
func NewArtistsGetAllDefault(code int) *ArtistsGetAllDefault {
	return &ArtistsGetAllDefault{
		_statusCode: code,
	}
}

/*
ArtistsGetAllDefault describes a response with status code -1, with default header values.

Error
*/
type ArtistsGetAllDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this artists get all default response has a 2xx status code
func (o *ArtistsGetAllDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this artists get all default response has a 3xx status code
func (o *ArtistsGetAllDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this artists get all default response has a 4xx status code
func (o *ArtistsGetAllDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this artists get all default response has a 5xx status code
func (o *ArtistsGetAllDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this artists get all default response a status code equal to that given
func (o *ArtistsGetAllDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the artists get all default response
func (o *ArtistsGetAllDefault) Code() int {
	return o._statusCode
}

func (o *ArtistsGetAllDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/Artists][%d] Artists_GetAll default %s", o._statusCode, payload)
}

func (o *ArtistsGetAllDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/Artists][%d] Artists_GetAll default %s", o._statusCode, payload)
}

func (o *ArtistsGetAllDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ArtistsGetAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
