// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// AssociationTypesGetReader is a Reader for the AssociationTypesGet structure.
type AssociationTypesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssociationTypesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssociationTypesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/AssociationTypes/{id}] AssociationTypes_Get", response, response.Code())
	}
}

// NewAssociationTypesGetOK creates a AssociationTypesGetOK with default headers values
func NewAssociationTypesGetOK() *AssociationTypesGetOK {
	return &AssociationTypesGetOK{}
}

/*
AssociationTypesGetOK describes a response with status code 200, with default header values.

OK
*/
type AssociationTypesGetOK struct {
	Payload *models.AssociationType
}

// IsSuccess returns true when this association types get o k response has a 2xx status code
func (o *AssociationTypesGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this association types get o k response has a 3xx status code
func (o *AssociationTypesGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this association types get o k response has a 4xx status code
func (o *AssociationTypesGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this association types get o k response has a 5xx status code
func (o *AssociationTypesGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this association types get o k response a status code equal to that given
func (o *AssociationTypesGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the association types get o k response
func (o *AssociationTypesGetOK) Code() int {
	return 200
}

func (o *AssociationTypesGetOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/AssociationTypes/{id}][%d] associationTypesGetOK  %+v", 200, o.Payload)
}

func (o *AssociationTypesGetOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/AssociationTypes/{id}][%d] associationTypesGetOK  %+v", 200, o.Payload)
}

func (o *AssociationTypesGetOK) GetPayload() *models.AssociationType {
	return o.Payload
}

func (o *AssociationTypesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssociationType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
