// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// BusinessUnitsGetSummariesReader is a Reader for the BusinessUnitsGetSummaries structure.
type BusinessUnitsGetSummariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BusinessUnitsGetSummariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBusinessUnitsGetSummariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBusinessUnitsGetSummariesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBusinessUnitsGetSummariesOK creates a BusinessUnitsGetSummariesOK with default headers values
func NewBusinessUnitsGetSummariesOK() *BusinessUnitsGetSummariesOK {
	return &BusinessUnitsGetSummariesOK{}
}

/*
BusinessUnitsGetSummariesOK describes a response with status code 200, with default header values.

OK
*/
type BusinessUnitsGetSummariesOK struct {
	Payload []*models.BusinessUnitSummary
}

// IsSuccess returns true when this business units get summaries o k response has a 2xx status code
func (o *BusinessUnitsGetSummariesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this business units get summaries o k response has a 3xx status code
func (o *BusinessUnitsGetSummariesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this business units get summaries o k response has a 4xx status code
func (o *BusinessUnitsGetSummariesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this business units get summaries o k response has a 5xx status code
func (o *BusinessUnitsGetSummariesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this business units get summaries o k response a status code equal to that given
func (o *BusinessUnitsGetSummariesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the business units get summaries o k response
func (o *BusinessUnitsGetSummariesOK) Code() int {
	return 200
}

func (o *BusinessUnitsGetSummariesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/BusinessUnits/Summary][%d] businessUnitsGetSummariesOK %s", 200, payload)
}

func (o *BusinessUnitsGetSummariesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/BusinessUnits/Summary][%d] businessUnitsGetSummariesOK %s", 200, payload)
}

func (o *BusinessUnitsGetSummariesOK) GetPayload() []*models.BusinessUnitSummary {
	return o.Payload
}

func (o *BusinessUnitsGetSummariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBusinessUnitsGetSummariesDefault creates a BusinessUnitsGetSummariesDefault with default headers values
func NewBusinessUnitsGetSummariesDefault(code int) *BusinessUnitsGetSummariesDefault {
	return &BusinessUnitsGetSummariesDefault{
		_statusCode: code,
	}
}

/*
BusinessUnitsGetSummariesDefault describes a response with status code -1, with default header values.

Error
*/
type BusinessUnitsGetSummariesDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this business units get summaries default response has a 2xx status code
func (o *BusinessUnitsGetSummariesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this business units get summaries default response has a 3xx status code
func (o *BusinessUnitsGetSummariesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this business units get summaries default response has a 4xx status code
func (o *BusinessUnitsGetSummariesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this business units get summaries default response has a 5xx status code
func (o *BusinessUnitsGetSummariesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this business units get summaries default response a status code equal to that given
func (o *BusinessUnitsGetSummariesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the business units get summaries default response
func (o *BusinessUnitsGetSummariesDefault) Code() int {
	return o._statusCode
}

func (o *BusinessUnitsGetSummariesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/BusinessUnits/Summary][%d] BusinessUnits_GetSummaries default %s", o._statusCode, payload)
}

func (o *BusinessUnitsGetSummariesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/BusinessUnits/Summary][%d] BusinessUnits_GetSummaries default %s", o._statusCode, payload)
}

func (o *BusinessUnitsGetSummariesDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *BusinessUnitsGetSummariesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
