// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// CardReaderTypesGetReader is a Reader for the CardReaderTypesGet structure.
type CardReaderTypesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CardReaderTypesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCardReaderTypesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCardReaderTypesGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCardReaderTypesGetOK creates a CardReaderTypesGetOK with default headers values
func NewCardReaderTypesGetOK() *CardReaderTypesGetOK {
	return &CardReaderTypesGetOK{}
}

/*
CardReaderTypesGetOK describes a response with status code 200, with default header values.

OK
*/
type CardReaderTypesGetOK struct {
	Payload *models.CardReaderType
}

// IsSuccess returns true when this card reader types get o k response has a 2xx status code
func (o *CardReaderTypesGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this card reader types get o k response has a 3xx status code
func (o *CardReaderTypesGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this card reader types get o k response has a 4xx status code
func (o *CardReaderTypesGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this card reader types get o k response has a 5xx status code
func (o *CardReaderTypesGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this card reader types get o k response a status code equal to that given
func (o *CardReaderTypesGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the card reader types get o k response
func (o *CardReaderTypesGetOK) Code() int {
	return 200
}

func (o *CardReaderTypesGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/CardReaderTypes/{id}][%d] cardReaderTypesGetOK %s", 200, payload)
}

func (o *CardReaderTypesGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/CardReaderTypes/{id}][%d] cardReaderTypesGetOK %s", 200, payload)
}

func (o *CardReaderTypesGetOK) GetPayload() *models.CardReaderType {
	return o.Payload
}

func (o *CardReaderTypesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CardReaderType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCardReaderTypesGetDefault creates a CardReaderTypesGetDefault with default headers values
func NewCardReaderTypesGetDefault(code int) *CardReaderTypesGetDefault {
	return &CardReaderTypesGetDefault{
		_statusCode: code,
	}
}

/*
CardReaderTypesGetDefault describes a response with status code -1, with default header values.

Error
*/
type CardReaderTypesGetDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this card reader types get default response has a 2xx status code
func (o *CardReaderTypesGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this card reader types get default response has a 3xx status code
func (o *CardReaderTypesGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this card reader types get default response has a 4xx status code
func (o *CardReaderTypesGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this card reader types get default response has a 5xx status code
func (o *CardReaderTypesGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this card reader types get default response a status code equal to that given
func (o *CardReaderTypesGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the card reader types get default response
func (o *CardReaderTypesGetDefault) Code() int {
	return o._statusCode
}

func (o *CardReaderTypesGetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/CardReaderTypes/{id}][%d] CardReaderTypes_Get default %s", o._statusCode, payload)
}

func (o *CardReaderTypesGetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/CardReaderTypes/{id}][%d] CardReaderTypes_Get default %s", o._statusCode, payload)
}

func (o *CardReaderTypesGetDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CardReaderTypesGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
