// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ContactPointPurposesGetSummariesReader is a Reader for the ContactPointPurposesGetSummaries structure.
type ContactPointPurposesGetSummariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContactPointPurposesGetSummariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContactPointPurposesGetSummariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewContactPointPurposesGetSummariesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewContactPointPurposesGetSummariesOK creates a ContactPointPurposesGetSummariesOK with default headers values
func NewContactPointPurposesGetSummariesOK() *ContactPointPurposesGetSummariesOK {
	return &ContactPointPurposesGetSummariesOK{}
}

/*
ContactPointPurposesGetSummariesOK describes a response with status code 200, with default header values.

OK
*/
type ContactPointPurposesGetSummariesOK struct {
	Payload []*models.ContactPointPurposeSummary
}

// IsSuccess returns true when this contact point purposes get summaries o k response has a 2xx status code
func (o *ContactPointPurposesGetSummariesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this contact point purposes get summaries o k response has a 3xx status code
func (o *ContactPointPurposesGetSummariesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this contact point purposes get summaries o k response has a 4xx status code
func (o *ContactPointPurposesGetSummariesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this contact point purposes get summaries o k response has a 5xx status code
func (o *ContactPointPurposesGetSummariesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this contact point purposes get summaries o k response a status code equal to that given
func (o *ContactPointPurposesGetSummariesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the contact point purposes get summaries o k response
func (o *ContactPointPurposesGetSummariesOK) Code() int {
	return 200
}

func (o *ContactPointPurposesGetSummariesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ContactPointPurposes/Summary][%d] contactPointPurposesGetSummariesOK %s", 200, payload)
}

func (o *ContactPointPurposesGetSummariesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ContactPointPurposes/Summary][%d] contactPointPurposesGetSummariesOK %s", 200, payload)
}

func (o *ContactPointPurposesGetSummariesOK) GetPayload() []*models.ContactPointPurposeSummary {
	return o.Payload
}

func (o *ContactPointPurposesGetSummariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewContactPointPurposesGetSummariesDefault creates a ContactPointPurposesGetSummariesDefault with default headers values
func NewContactPointPurposesGetSummariesDefault(code int) *ContactPointPurposesGetSummariesDefault {
	return &ContactPointPurposesGetSummariesDefault{
		_statusCode: code,
	}
}

/*
ContactPointPurposesGetSummariesDefault describes a response with status code -1, with default header values.

Error
*/
type ContactPointPurposesGetSummariesDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this contact point purposes get summaries default response has a 2xx status code
func (o *ContactPointPurposesGetSummariesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this contact point purposes get summaries default response has a 3xx status code
func (o *ContactPointPurposesGetSummariesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this contact point purposes get summaries default response has a 4xx status code
func (o *ContactPointPurposesGetSummariesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this contact point purposes get summaries default response has a 5xx status code
func (o *ContactPointPurposesGetSummariesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this contact point purposes get summaries default response a status code equal to that given
func (o *ContactPointPurposesGetSummariesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the contact point purposes get summaries default response
func (o *ContactPointPurposesGetSummariesDefault) Code() int {
	return o._statusCode
}

func (o *ContactPointPurposesGetSummariesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ContactPointPurposes/Summary][%d] ContactPointPurposes_GetSummaries default %s", o._statusCode, payload)
}

func (o *ContactPointPurposesGetSummariesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/ContactPointPurposes/Summary][%d] ContactPointPurposes_GetSummaries default %s", o._statusCode, payload)
}

func (o *ContactPointPurposesGetSummariesDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ContactPointPurposesGetSummariesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
