// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewControlGroupUserGroupsGetParams creates a new ControlGroupUserGroupsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewControlGroupUserGroupsGetParams() *ControlGroupUserGroupsGetParams {
	return &ControlGroupUserGroupsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewControlGroupUserGroupsGetParamsWithTimeout creates a new ControlGroupUserGroupsGetParams object
// with the ability to set a timeout on a request.
func NewControlGroupUserGroupsGetParamsWithTimeout(timeout time.Duration) *ControlGroupUserGroupsGetParams {
	return &ControlGroupUserGroupsGetParams{
		timeout: timeout,
	}
}

// NewControlGroupUserGroupsGetParamsWithContext creates a new ControlGroupUserGroupsGetParams object
// with the ability to set a context for a request.
func NewControlGroupUserGroupsGetParamsWithContext(ctx context.Context) *ControlGroupUserGroupsGetParams {
	return &ControlGroupUserGroupsGetParams{
		Context: ctx,
	}
}

// NewControlGroupUserGroupsGetParamsWithHTTPClient creates a new ControlGroupUserGroupsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewControlGroupUserGroupsGetParamsWithHTTPClient(client *http.Client) *ControlGroupUserGroupsGetParams {
	return &ControlGroupUserGroupsGetParams{
		HTTPClient: client,
	}
}

/*
ControlGroupUserGroupsGetParams contains all the parameters to send to the API endpoint

	for the control group user groups get operation.

	Typically these are written to a http.Request.
*/
type ControlGroupUserGroupsGetParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the control group user groups get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ControlGroupUserGroupsGetParams) WithDefaults() *ControlGroupUserGroupsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the control group user groups get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ControlGroupUserGroupsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) WithTimeout(timeout time.Duration) *ControlGroupUserGroupsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) WithContext(ctx context.Context) *ControlGroupUserGroupsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) WithHTTPClient(client *http.Client) *ControlGroupUserGroupsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) WithID(id string) *ControlGroupUserGroupsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the control group user groups get params
func (o *ControlGroupUserGroupsGetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *ControlGroupUserGroupsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
