// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// CustomGetMetadataReader is a Reader for the CustomGetMetadata structure.
type CustomGetMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomGetMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomGetMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCustomGetMetadataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCustomGetMetadataOK creates a CustomGetMetadataOK with default headers values
func NewCustomGetMetadataOK() *CustomGetMetadataOK {
	return &CustomGetMetadataOK{}
}

/*
CustomGetMetadataOK describes a response with status code 200, with default header values.

OK
*/
type CustomGetMetadataOK struct {
	Payload []*models.TableMetadata
}

// IsSuccess returns true when this custom get metadata o k response has a 2xx status code
func (o *CustomGetMetadataOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this custom get metadata o k response has a 3xx status code
func (o *CustomGetMetadataOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom get metadata o k response has a 4xx status code
func (o *CustomGetMetadataOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom get metadata o k response has a 5xx status code
func (o *CustomGetMetadataOK) IsServerError() bool {
	return false
}

// IsCode returns true when this custom get metadata o k response a status code equal to that given
func (o *CustomGetMetadataOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the custom get metadata o k response
func (o *CustomGetMetadataOK) Code() int {
	return 200
}

func (o *CustomGetMetadataOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Custom/Metadata][%d] customGetMetadataOK %s", 200, payload)
}

func (o *CustomGetMetadataOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Custom/Metadata][%d] customGetMetadataOK %s", 200, payload)
}

func (o *CustomGetMetadataOK) GetPayload() []*models.TableMetadata {
	return o.Payload
}

func (o *CustomGetMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCustomGetMetadataDefault creates a CustomGetMetadataDefault with default headers values
func NewCustomGetMetadataDefault(code int) *CustomGetMetadataDefault {
	return &CustomGetMetadataDefault{
		_statusCode: code,
	}
}

/*
CustomGetMetadataDefault describes a response with status code -1, with default header values.

Error
*/
type CustomGetMetadataDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this custom get metadata default response has a 2xx status code
func (o *CustomGetMetadataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this custom get metadata default response has a 3xx status code
func (o *CustomGetMetadataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this custom get metadata default response has a 4xx status code
func (o *CustomGetMetadataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this custom get metadata default response has a 5xx status code
func (o *CustomGetMetadataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this custom get metadata default response a status code equal to that given
func (o *CustomGetMetadataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the custom get metadata default response
func (o *CustomGetMetadataDefault) Code() int {
	return o._statusCode
}

func (o *CustomGetMetadataDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Custom/Metadata][%d] Custom_GetMetadata default %s", o._statusCode, payload)
}

func (o *CustomGetMetadataDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /Custom/Metadata][%d] Custom_GetMetadata default %s", o._statusCode, payload)
}

func (o *CustomGetMetadataDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CustomGetMetadataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
