// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// FormatsGetAllReader is a Reader for the FormatsGetAll structure.
type FormatsGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FormatsGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFormatsGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/Formats] Formats_GetAll", response, response.Code())
	}
}

// NewFormatsGetAllOK creates a FormatsGetAllOK with default headers values
func NewFormatsGetAllOK() *FormatsGetAllOK {
	return &FormatsGetAllOK{}
}

/*
FormatsGetAllOK describes a response with status code 200, with default header values.

OK
*/
type FormatsGetAllOK struct {
	Payload []*models.Format
}

// IsSuccess returns true when this formats get all o k response has a 2xx status code
func (o *FormatsGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this formats get all o k response has a 3xx status code
func (o *FormatsGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this formats get all o k response has a 4xx status code
func (o *FormatsGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this formats get all o k response has a 5xx status code
func (o *FormatsGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this formats get all o k response a status code equal to that given
func (o *FormatsGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the formats get all o k response
func (o *FormatsGetAllOK) Code() int {
	return 200
}

func (o *FormatsGetAllOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/Formats][%d] formatsGetAllOK  %+v", 200, o.Payload)
}

func (o *FormatsGetAllOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/Formats][%d] formatsGetAllOK  %+v", 200, o.Payload)
}

func (o *FormatsGetAllOK) GetPayload() []*models.Format {
	return o.Payload
}

func (o *FormatsGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
