// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// GiftAidContactMethodsGetAllReader is a Reader for the GiftAidContactMethodsGetAll structure.
type GiftAidContactMethodsGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GiftAidContactMethodsGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGiftAidContactMethodsGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/GiftAidContactMethods] GiftAidContactMethods_GetAll", response, response.Code())
	}
}

// NewGiftAidContactMethodsGetAllOK creates a GiftAidContactMethodsGetAllOK with default headers values
func NewGiftAidContactMethodsGetAllOK() *GiftAidContactMethodsGetAllOK {
	return &GiftAidContactMethodsGetAllOK{}
}

/*
GiftAidContactMethodsGetAllOK describes a response with status code 200, with default header values.

OK
*/
type GiftAidContactMethodsGetAllOK struct {
	Payload []*models.GiftAidContactMethod
}

// IsSuccess returns true when this gift aid contact methods get all o k response has a 2xx status code
func (o *GiftAidContactMethodsGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this gift aid contact methods get all o k response has a 3xx status code
func (o *GiftAidContactMethodsGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this gift aid contact methods get all o k response has a 4xx status code
func (o *GiftAidContactMethodsGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this gift aid contact methods get all o k response has a 5xx status code
func (o *GiftAidContactMethodsGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this gift aid contact methods get all o k response a status code equal to that given
func (o *GiftAidContactMethodsGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the gift aid contact methods get all o k response
func (o *GiftAidContactMethodsGetAllOK) Code() int {
	return 200
}

func (o *GiftAidContactMethodsGetAllOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/GiftAidContactMethods][%d] giftAidContactMethodsGetAllOK  %+v", 200, o.Payload)
}

func (o *GiftAidContactMethodsGetAllOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/GiftAidContactMethods][%d] giftAidContactMethodsGetAllOK  %+v", 200, o.Payload)
}

func (o *GiftAidContactMethodsGetAllOK) GetPayload() []*models.GiftAidContactMethod {
	return o.Payload
}

func (o *GiftAidContactMethodsGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
