// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInterestCategoriesGetSummariesParams creates a new InterestCategoriesGetSummariesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInterestCategoriesGetSummariesParams() *InterestCategoriesGetSummariesParams {
	return &InterestCategoriesGetSummariesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInterestCategoriesGetSummariesParamsWithTimeout creates a new InterestCategoriesGetSummariesParams object
// with the ability to set a timeout on a request.
func NewInterestCategoriesGetSummariesParamsWithTimeout(timeout time.Duration) *InterestCategoriesGetSummariesParams {
	return &InterestCategoriesGetSummariesParams{
		timeout: timeout,
	}
}

// NewInterestCategoriesGetSummariesParamsWithContext creates a new InterestCategoriesGetSummariesParams object
// with the ability to set a context for a request.
func NewInterestCategoriesGetSummariesParamsWithContext(ctx context.Context) *InterestCategoriesGetSummariesParams {
	return &InterestCategoriesGetSummariesParams{
		Context: ctx,
	}
}

// NewInterestCategoriesGetSummariesParamsWithHTTPClient creates a new InterestCategoriesGetSummariesParams object
// with the ability to set a custom HTTPClient for a request.
func NewInterestCategoriesGetSummariesParamsWithHTTPClient(client *http.Client) *InterestCategoriesGetSummariesParams {
	return &InterestCategoriesGetSummariesParams{
		HTTPClient: client,
	}
}

/*
InterestCategoriesGetSummariesParams contains all the parameters to send to the API endpoint

	for the interest categories get summaries operation.

	Typically these are written to a http.Request.
*/
type InterestCategoriesGetSummariesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the interest categories get summaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InterestCategoriesGetSummariesParams) WithDefaults() *InterestCategoriesGetSummariesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the interest categories get summaries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InterestCategoriesGetSummariesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) WithTimeout(timeout time.Duration) *InterestCategoriesGetSummariesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) WithContext(ctx context.Context) *InterestCategoriesGetSummariesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) WithHTTPClient(client *http.Client) *InterestCategoriesGetSummariesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the interest categories get summaries params
func (o *InterestCategoriesGetSummariesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *InterestCategoriesGetSummariesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
