// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// InterestsGetReader is a Reader for the InterestsGet structure.
type InterestsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InterestsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInterestsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewInterestsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewInterestsGetOK creates a InterestsGetOK with default headers values
func NewInterestsGetOK() *InterestsGetOK {
	return &InterestsGetOK{}
}

/*
InterestsGetOK describes a response with status code 200, with default header values.

OK
*/
type InterestsGetOK struct {
	Payload *models.Interest
}

// IsSuccess returns true when this interests get o k response has a 2xx status code
func (o *InterestsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this interests get o k response has a 3xx status code
func (o *InterestsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this interests get o k response has a 4xx status code
func (o *InterestsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this interests get o k response has a 5xx status code
func (o *InterestsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this interests get o k response a status code equal to that given
func (o *InterestsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the interests get o k response
func (o *InterestsGetOK) Code() int {
	return 200
}

func (o *InterestsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /CRM/Interests/{interestId}][%d] interestsGetOK %s", 200, payload)
}

func (o *InterestsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /CRM/Interests/{interestId}][%d] interestsGetOK %s", 200, payload)
}

func (o *InterestsGetOK) GetPayload() *models.Interest {
	return o.Payload
}

func (o *InterestsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Interest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInterestsGetDefault creates a InterestsGetDefault with default headers values
func NewInterestsGetDefault(code int) *InterestsGetDefault {
	return &InterestsGetDefault{
		_statusCode: code,
	}
}

/*
InterestsGetDefault describes a response with status code -1, with default header values.

Error
*/
type InterestsGetDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this interests get default response has a 2xx status code
func (o *InterestsGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this interests get default response has a 3xx status code
func (o *InterestsGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this interests get default response has a 4xx status code
func (o *InterestsGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this interests get default response has a 5xx status code
func (o *InterestsGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this interests get default response a status code equal to that given
func (o *InterestsGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the interests get default response
func (o *InterestsGetDefault) Code() int {
	return o._statusCode
}

func (o *InterestsGetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /CRM/Interests/{interestId}][%d] Interests_Get default %s", o._statusCode, payload)
}

func (o *InterestsGetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /CRM/Interests/{interestId}][%d] Interests_Get default %s", o._statusCode, payload)
}

func (o *InterestsGetDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *InterestsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
