// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PaymentMethodGroupsGetReader is a Reader for the PaymentMethodGroupsGet structure.
type PaymentMethodGroupsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PaymentMethodGroupsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPaymentMethodGroupsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/PaymentMethodGroups/{id}] PaymentMethodGroups_Get", response, response.Code())
	}
}

// NewPaymentMethodGroupsGetOK creates a PaymentMethodGroupsGetOK with default headers values
func NewPaymentMethodGroupsGetOK() *PaymentMethodGroupsGetOK {
	return &PaymentMethodGroupsGetOK{}
}

/*
PaymentMethodGroupsGetOK describes a response with status code 200, with default header values.

OK
*/
type PaymentMethodGroupsGetOK struct {
	Payload *models.PaymentMethodGroup
}

// IsSuccess returns true when this payment method groups get o k response has a 2xx status code
func (o *PaymentMethodGroupsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this payment method groups get o k response has a 3xx status code
func (o *PaymentMethodGroupsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this payment method groups get o k response has a 4xx status code
func (o *PaymentMethodGroupsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this payment method groups get o k response has a 5xx status code
func (o *PaymentMethodGroupsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this payment method groups get o k response a status code equal to that given
func (o *PaymentMethodGroupsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the payment method groups get o k response
func (o *PaymentMethodGroupsGetOK) Code() int {
	return 200
}

func (o *PaymentMethodGroupsGetOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/PaymentMethodGroups/{id}][%d] paymentMethodGroupsGetOK  %+v", 200, o.Payload)
}

func (o *PaymentMethodGroupsGetOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/PaymentMethodGroups/{id}][%d] paymentMethodGroupsGetOK  %+v", 200, o.Payload)
}

func (o *PaymentMethodGroupsGetOK) GetPayload() *models.PaymentMethodGroup {
	return o.Payload
}

func (o *PaymentMethodGroupsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentMethodGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
