// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PhoneIndicatorsGetAllReader is a Reader for the PhoneIndicatorsGetAll structure.
type PhoneIndicatorsGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PhoneIndicatorsGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPhoneIndicatorsGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPhoneIndicatorsGetAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPhoneIndicatorsGetAllOK creates a PhoneIndicatorsGetAllOK with default headers values
func NewPhoneIndicatorsGetAllOK() *PhoneIndicatorsGetAllOK {
	return &PhoneIndicatorsGetAllOK{}
}

/*
PhoneIndicatorsGetAllOK describes a response with status code 200, with default header values.

OK
*/
type PhoneIndicatorsGetAllOK struct {
	Payload []*models.PhoneIndicator
}

// IsSuccess returns true when this phone indicators get all o k response has a 2xx status code
func (o *PhoneIndicatorsGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this phone indicators get all o k response has a 3xx status code
func (o *PhoneIndicatorsGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this phone indicators get all o k response has a 4xx status code
func (o *PhoneIndicatorsGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this phone indicators get all o k response has a 5xx status code
func (o *PhoneIndicatorsGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this phone indicators get all o k response a status code equal to that given
func (o *PhoneIndicatorsGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the phone indicators get all o k response
func (o *PhoneIndicatorsGetAllOK) Code() int {
	return 200
}

func (o *PhoneIndicatorsGetAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/PhoneIndicators][%d] phoneIndicatorsGetAllOK %s", 200, payload)
}

func (o *PhoneIndicatorsGetAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/PhoneIndicators][%d] phoneIndicatorsGetAllOK %s", 200, payload)
}

func (o *PhoneIndicatorsGetAllOK) GetPayload() []*models.PhoneIndicator {
	return o.Payload
}

func (o *PhoneIndicatorsGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPhoneIndicatorsGetAllDefault creates a PhoneIndicatorsGetAllDefault with default headers values
func NewPhoneIndicatorsGetAllDefault(code int) *PhoneIndicatorsGetAllDefault {
	return &PhoneIndicatorsGetAllDefault{
		_statusCode: code,
	}
}

/*
PhoneIndicatorsGetAllDefault describes a response with status code -1, with default header values.

Error
*/
type PhoneIndicatorsGetAllDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this phone indicators get all default response has a 2xx status code
func (o *PhoneIndicatorsGetAllDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this phone indicators get all default response has a 3xx status code
func (o *PhoneIndicatorsGetAllDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this phone indicators get all default response has a 4xx status code
func (o *PhoneIndicatorsGetAllDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this phone indicators get all default response has a 5xx status code
func (o *PhoneIndicatorsGetAllDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this phone indicators get all default response a status code equal to that given
func (o *PhoneIndicatorsGetAllDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the phone indicators get all default response
func (o *PhoneIndicatorsGetAllDefault) Code() int {
	return o._statusCode
}

func (o *PhoneIndicatorsGetAllDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/PhoneIndicators][%d] PhoneIndicators_GetAll default %s", o._statusCode, payload)
}

func (o *PhoneIndicatorsGetAllDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/PhoneIndicators][%d] PhoneIndicators_GetAll default %s", o._statusCode, payload)
}

func (o *PhoneIndicatorsGetAllDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PhoneIndicatorsGetAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
