// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PricingRuleMessageTypesGetReader is a Reader for the PricingRuleMessageTypesGet structure.
type PricingRuleMessageTypesGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PricingRuleMessageTypesGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPricingRuleMessageTypesGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/PricingRuleMessageTypes/{id}] PricingRuleMessageTypes_Get", response, response.Code())
	}
}

// NewPricingRuleMessageTypesGetOK creates a PricingRuleMessageTypesGetOK with default headers values
func NewPricingRuleMessageTypesGetOK() *PricingRuleMessageTypesGetOK {
	return &PricingRuleMessageTypesGetOK{}
}

/*
PricingRuleMessageTypesGetOK describes a response with status code 200, with default header values.

OK
*/
type PricingRuleMessageTypesGetOK struct {
	Payload *models.PricingRuleMessageType
}

// IsSuccess returns true when this pricing rule message types get o k response has a 2xx status code
func (o *PricingRuleMessageTypesGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this pricing rule message types get o k response has a 3xx status code
func (o *PricingRuleMessageTypesGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this pricing rule message types get o k response has a 4xx status code
func (o *PricingRuleMessageTypesGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this pricing rule message types get o k response has a 5xx status code
func (o *PricingRuleMessageTypesGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this pricing rule message types get o k response a status code equal to that given
func (o *PricingRuleMessageTypesGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the pricing rule message types get o k response
func (o *PricingRuleMessageTypesGetOK) Code() int {
	return 200
}

func (o *PricingRuleMessageTypesGetOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/PricingRuleMessageTypes/{id}][%d] pricingRuleMessageTypesGetOK  %+v", 200, o.Payload)
}

func (o *PricingRuleMessageTypesGetOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/PricingRuleMessageTypes/{id}][%d] pricingRuleMessageTypesGetOK  %+v", 200, o.Payload)
}

func (o *PricingRuleMessageTypesGetOK) GetPayload() *models.PricingRuleMessageType {
	return o.Payload
}

func (o *PricingRuleMessageTypesGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PricingRuleMessageType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
