// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PriceEventsGetAllReader is a Reader for the PriceEventsGetAll structure.
type PriceEventsGetAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PriceEventsGetAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPriceEventsGetAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPriceEventsGetAllDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPriceEventsGetAllOK creates a PriceEventsGetAllOK with default headers values
func NewPriceEventsGetAllOK() *PriceEventsGetAllOK {
	return &PriceEventsGetAllOK{}
}

/*
PriceEventsGetAllOK describes a response with status code 200, with default header values.

OK
*/
type PriceEventsGetAllOK struct {
	Payload []*models.PriceEvent
}

// IsSuccess returns true when this price events get all o k response has a 2xx status code
func (o *PriceEventsGetAllOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this price events get all o k response has a 3xx status code
func (o *PriceEventsGetAllOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this price events get all o k response has a 4xx status code
func (o *PriceEventsGetAllOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this price events get all o k response has a 5xx status code
func (o *PriceEventsGetAllOK) IsServerError() bool {
	return false
}

// IsCode returns true when this price events get all o k response a status code equal to that given
func (o *PriceEventsGetAllOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the price events get all o k response
func (o *PriceEventsGetAllOK) Code() int {
	return 200
}

func (o *PriceEventsGetAllOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents][%d] priceEventsGetAllOK %s", 200, payload)
}

func (o *PriceEventsGetAllOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents][%d] priceEventsGetAllOK %s", 200, payload)
}

func (o *PriceEventsGetAllOK) GetPayload() []*models.PriceEvent {
	return o.Payload
}

func (o *PriceEventsGetAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPriceEventsGetAllDefault creates a PriceEventsGetAllDefault with default headers values
func NewPriceEventsGetAllDefault(code int) *PriceEventsGetAllDefault {
	return &PriceEventsGetAllDefault{
		_statusCode: code,
	}
}

/*
PriceEventsGetAllDefault describes a response with status code -1, with default header values.

Error
*/
type PriceEventsGetAllDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this price events get all default response has a 2xx status code
func (o *PriceEventsGetAllDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this price events get all default response has a 3xx status code
func (o *PriceEventsGetAllDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this price events get all default response has a 4xx status code
func (o *PriceEventsGetAllDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this price events get all default response has a 5xx status code
func (o *PriceEventsGetAllDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this price events get all default response a status code equal to that given
func (o *PriceEventsGetAllDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the price events get all default response
func (o *PriceEventsGetAllDefault) Code() int {
	return o._statusCode
}

func (o *PriceEventsGetAllDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents][%d] PriceEvents_GetAll default %s", o._statusCode, payload)
}

func (o *PriceEventsGetAllDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents][%d] PriceEvents_GetAll default %s", o._statusCode, payload)
}

func (o *PriceEventsGetAllDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PriceEventsGetAllDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
