// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PriceEventsGetDatesReader is a Reader for the PriceEventsGetDates structure.
type PriceEventsGetDatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PriceEventsGetDatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPriceEventsGetDatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPriceEventsGetDatesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPriceEventsGetDatesOK creates a PriceEventsGetDatesOK with default headers values
func NewPriceEventsGetDatesOK() *PriceEventsGetDatesOK {
	return &PriceEventsGetDatesOK{}
}

/*
PriceEventsGetDatesOK describes a response with status code 200, with default header values.

OK
*/
type PriceEventsGetDatesOK struct {
	Payload []strfmt.DateTime
}

// IsSuccess returns true when this price events get dates o k response has a 2xx status code
func (o *PriceEventsGetDatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this price events get dates o k response has a 3xx status code
func (o *PriceEventsGetDatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this price events get dates o k response has a 4xx status code
func (o *PriceEventsGetDatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this price events get dates o k response has a 5xx status code
func (o *PriceEventsGetDatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this price events get dates o k response a status code equal to that given
func (o *PriceEventsGetDatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the price events get dates o k response
func (o *PriceEventsGetDatesOK) Code() int {
	return 200
}

func (o *PriceEventsGetDatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents/Dates][%d] priceEventsGetDatesOK %s", 200, payload)
}

func (o *PriceEventsGetDatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents/Dates][%d] priceEventsGetDatesOK %s", 200, payload)
}

func (o *PriceEventsGetDatesOK) GetPayload() []strfmt.DateTime {
	return o.Payload
}

func (o *PriceEventsGetDatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPriceEventsGetDatesDefault creates a PriceEventsGetDatesDefault with default headers values
func NewPriceEventsGetDatesDefault(code int) *PriceEventsGetDatesDefault {
	return &PriceEventsGetDatesDefault{
		_statusCode: code,
	}
}

/*
PriceEventsGetDatesDefault describes a response with status code -1, with default header values.

Error
*/
type PriceEventsGetDatesDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this price events get dates default response has a 2xx status code
func (o *PriceEventsGetDatesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this price events get dates default response has a 3xx status code
func (o *PriceEventsGetDatesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this price events get dates default response has a 4xx status code
func (o *PriceEventsGetDatesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this price events get dates default response has a 5xx status code
func (o *PriceEventsGetDatesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this price events get dates default response a status code equal to that given
func (o *PriceEventsGetDatesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the price events get dates default response
func (o *PriceEventsGetDatesDefault) Code() int {
	return o._statusCode
}

func (o *PriceEventsGetDatesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents/Dates][%d] PriceEvents_GetDates default %s", o._statusCode, payload)
}

func (o *PriceEventsGetDatesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/PriceEvents/Dates][%d] PriceEvents_GetDates default %s", o._statusCode, payload)
}

func (o *PriceEventsGetDatesDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PriceEventsGetDatesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
