// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ProductionSeasonMembershipOrganizationsGetReader is a Reader for the ProductionSeasonMembershipOrganizationsGet structure.
type ProductionSeasonMembershipOrganizationsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProductionSeasonMembershipOrganizationsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewProductionSeasonMembershipOrganizationsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewProductionSeasonMembershipOrganizationsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProductionSeasonMembershipOrganizationsGetOK creates a ProductionSeasonMembershipOrganizationsGetOK with default headers values
func NewProductionSeasonMembershipOrganizationsGetOK() *ProductionSeasonMembershipOrganizationsGetOK {
	return &ProductionSeasonMembershipOrganizationsGetOK{}
}

/*
ProductionSeasonMembershipOrganizationsGetOK describes a response with status code 200, with default header values.

OK
*/
type ProductionSeasonMembershipOrganizationsGetOK struct {
	Payload *models.ProductionSeasonMembershipOrganization
}

// IsSuccess returns true when this production season membership organizations get o k response has a 2xx status code
func (o *ProductionSeasonMembershipOrganizationsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this production season membership organizations get o k response has a 3xx status code
func (o *ProductionSeasonMembershipOrganizationsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this production season membership organizations get o k response has a 4xx status code
func (o *ProductionSeasonMembershipOrganizationsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this production season membership organizations get o k response has a 5xx status code
func (o *ProductionSeasonMembershipOrganizationsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this production season membership organizations get o k response a status code equal to that given
func (o *ProductionSeasonMembershipOrganizationsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the production season membership organizations get o k response
func (o *ProductionSeasonMembershipOrganizationsGetOK) Code() int {
	return 200
}

func (o *ProductionSeasonMembershipOrganizationsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/ProductionSeasonMembershipOrganizations/{id}][%d] productionSeasonMembershipOrganizationsGetOK %s", 200, payload)
}

func (o *ProductionSeasonMembershipOrganizationsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/ProductionSeasonMembershipOrganizations/{id}][%d] productionSeasonMembershipOrganizationsGetOK %s", 200, payload)
}

func (o *ProductionSeasonMembershipOrganizationsGetOK) GetPayload() *models.ProductionSeasonMembershipOrganization {
	return o.Payload
}

func (o *ProductionSeasonMembershipOrganizationsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProductionSeasonMembershipOrganization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProductionSeasonMembershipOrganizationsGetDefault creates a ProductionSeasonMembershipOrganizationsGetDefault with default headers values
func NewProductionSeasonMembershipOrganizationsGetDefault(code int) *ProductionSeasonMembershipOrganizationsGetDefault {
	return &ProductionSeasonMembershipOrganizationsGetDefault{
		_statusCode: code,
	}
}

/*
ProductionSeasonMembershipOrganizationsGetDefault describes a response with status code -1, with default header values.

Error
*/
type ProductionSeasonMembershipOrganizationsGetDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this production season membership organizations get default response has a 2xx status code
func (o *ProductionSeasonMembershipOrganizationsGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this production season membership organizations get default response has a 3xx status code
func (o *ProductionSeasonMembershipOrganizationsGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this production season membership organizations get default response has a 4xx status code
func (o *ProductionSeasonMembershipOrganizationsGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this production season membership organizations get default response has a 5xx status code
func (o *ProductionSeasonMembershipOrganizationsGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this production season membership organizations get default response a status code equal to that given
func (o *ProductionSeasonMembershipOrganizationsGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the production season membership organizations get default response
func (o *ProductionSeasonMembershipOrganizationsGetDefault) Code() int {
	return o._statusCode
}

func (o *ProductionSeasonMembershipOrganizationsGetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/ProductionSeasonMembershipOrganizations/{id}][%d] ProductionSeasonMembershipOrganizations_Get default %s", o._statusCode, payload)
}

func (o *ProductionSeasonMembershipOrganizationsGetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /TXN/ProductionSeasonMembershipOrganizations/{id}][%d] ProductionSeasonMembershipOrganizations_Get default %s", o._statusCode, payload)
}

func (o *ProductionSeasonMembershipOrganizationsGetDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ProductionSeasonMembershipOrganizationsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
