// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPronounsGetParams creates a new PronounsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPronounsGetParams() *PronounsGetParams {
	return &PronounsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPronounsGetParamsWithTimeout creates a new PronounsGetParams object
// with the ability to set a timeout on a request.
func NewPronounsGetParamsWithTimeout(timeout time.Duration) *PronounsGetParams {
	return &PronounsGetParams{
		timeout: timeout,
	}
}

// NewPronounsGetParamsWithContext creates a new PronounsGetParams object
// with the ability to set a context for a request.
func NewPronounsGetParamsWithContext(ctx context.Context) *PronounsGetParams {
	return &PronounsGetParams{
		Context: ctx,
	}
}

// NewPronounsGetParamsWithHTTPClient creates a new PronounsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewPronounsGetParamsWithHTTPClient(client *http.Client) *PronounsGetParams {
	return &PronounsGetParams{
		HTTPClient: client,
	}
}

/*
PronounsGetParams contains all the parameters to send to the API endpoint

	for the pronouns get operation.

	Typically these are written to a http.Request.
*/
type PronounsGetParams struct {

	// ID.
	ID string

	// MaintenanceMode.
	MaintenanceMode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the pronouns get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PronounsGetParams) WithDefaults() *PronounsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the pronouns get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PronounsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the pronouns get params
func (o *PronounsGetParams) WithTimeout(timeout time.Duration) *PronounsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pronouns get params
func (o *PronounsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pronouns get params
func (o *PronounsGetParams) WithContext(ctx context.Context) *PronounsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pronouns get params
func (o *PronounsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pronouns get params
func (o *PronounsGetParams) WithHTTPClient(client *http.Client) *PronounsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pronouns get params
func (o *PronounsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pronouns get params
func (o *PronounsGetParams) WithID(id string) *PronounsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pronouns get params
func (o *PronounsGetParams) SetID(id string) {
	o.ID = id
}

// WithMaintenanceMode adds the maintenanceMode to the pronouns get params
func (o *PronounsGetParams) WithMaintenanceMode(maintenanceMode *string) *PronounsGetParams {
	o.SetMaintenanceMode(maintenanceMode)
	return o
}

// SetMaintenanceMode adds the maintenanceMode to the pronouns get params
func (o *PronounsGetParams) SetMaintenanceMode(maintenanceMode *string) {
	o.MaintenanceMode = maintenanceMode
}

// WriteToRequest writes these params to a swagger request
func (o *PronounsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.MaintenanceMode != nil {

		// query param maintenanceMode
		var qrMaintenanceMode string

		if o.MaintenanceMode != nil {
			qrMaintenanceMode = *o.MaintenanceMode
		}
		qMaintenanceMode := qrMaintenanceMode
		if qMaintenanceMode != "" {

			if err := r.SetQueryParam("maintenanceMode", qMaintenanceMode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
