// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// QueryElementFiltersGetDataForReader is a Reader for the QueryElementFiltersGetDataFor structure.
type QueryElementFiltersGetDataForReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryElementFiltersGetDataForReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryElementFiltersGetDataForOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /Reporting/QueryElementFilters/Data] QueryElementFilters_GetDataFor", response, response.Code())
	}
}

// NewQueryElementFiltersGetDataForOK creates a QueryElementFiltersGetDataForOK with default headers values
func NewQueryElementFiltersGetDataForOK() *QueryElementFiltersGetDataForOK {
	return &QueryElementFiltersGetDataForOK{}
}

/*
QueryElementFiltersGetDataForOK describes a response with status code 200, with default header values.

OK
*/
type QueryElementFiltersGetDataForOK struct {
	Payload []*models.FilterDataItem
}

// IsSuccess returns true when this query element filters get data for o k response has a 2xx status code
func (o *QueryElementFiltersGetDataForOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query element filters get data for o k response has a 3xx status code
func (o *QueryElementFiltersGetDataForOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query element filters get data for o k response has a 4xx status code
func (o *QueryElementFiltersGetDataForOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query element filters get data for o k response has a 5xx status code
func (o *QueryElementFiltersGetDataForOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query element filters get data for o k response a status code equal to that given
func (o *QueryElementFiltersGetDataForOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query element filters get data for o k response
func (o *QueryElementFiltersGetDataForOK) Code() int {
	return 200
}

func (o *QueryElementFiltersGetDataForOK) Error() string {
	return fmt.Sprintf("[GET /Reporting/QueryElementFilters/Data][%d] queryElementFiltersGetDataForOK  %+v", 200, o.Payload)
}

func (o *QueryElementFiltersGetDataForOK) String() string {
	return fmt.Sprintf("[GET /Reporting/QueryElementFilters/Data][%d] queryElementFiltersGetDataForOK  %+v", 200, o.Payload)
}

func (o *QueryElementFiltersGetDataForOK) GetPayload() []*models.FilterDataItem {
	return o.Payload
}

func (o *QueryElementFiltersGetDataForOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
