// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// RankTypesGetSummariesReader is a Reader for the RankTypesGetSummaries structure.
type RankTypesGetSummariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RankTypesGetSummariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRankTypesGetSummariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRankTypesGetSummariesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRankTypesGetSummariesOK creates a RankTypesGetSummariesOK with default headers values
func NewRankTypesGetSummariesOK() *RankTypesGetSummariesOK {
	return &RankTypesGetSummariesOK{}
}

/*
RankTypesGetSummariesOK describes a response with status code 200, with default header values.

OK
*/
type RankTypesGetSummariesOK struct {
	Payload []*models.RankTypeSummary
}

// IsSuccess returns true when this rank types get summaries o k response has a 2xx status code
func (o *RankTypesGetSummariesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this rank types get summaries o k response has a 3xx status code
func (o *RankTypesGetSummariesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this rank types get summaries o k response has a 4xx status code
func (o *RankTypesGetSummariesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this rank types get summaries o k response has a 5xx status code
func (o *RankTypesGetSummariesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this rank types get summaries o k response a status code equal to that given
func (o *RankTypesGetSummariesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the rank types get summaries o k response
func (o *RankTypesGetSummariesOK) Code() int {
	return 200
}

func (o *RankTypesGetSummariesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/RankTypes/Summary][%d] rankTypesGetSummariesOK %s", 200, payload)
}

func (o *RankTypesGetSummariesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/RankTypes/Summary][%d] rankTypesGetSummariesOK %s", 200, payload)
}

func (o *RankTypesGetSummariesOK) GetPayload() []*models.RankTypeSummary {
	return o.Payload
}

func (o *RankTypesGetSummariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRankTypesGetSummariesDefault creates a RankTypesGetSummariesDefault with default headers values
func NewRankTypesGetSummariesDefault(code int) *RankTypesGetSummariesDefault {
	return &RankTypesGetSummariesDefault{
		_statusCode: code,
	}
}

/*
RankTypesGetSummariesDefault describes a response with status code -1, with default header values.

Error
*/
type RankTypesGetSummariesDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this rank types get summaries default response has a 2xx status code
func (o *RankTypesGetSummariesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this rank types get summaries default response has a 3xx status code
func (o *RankTypesGetSummariesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this rank types get summaries default response has a 4xx status code
func (o *RankTypesGetSummariesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this rank types get summaries default response has a 5xx status code
func (o *RankTypesGetSummariesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this rank types get summaries default response a status code equal to that given
func (o *RankTypesGetSummariesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the rank types get summaries default response
func (o *RankTypesGetSummariesDefault) Code() int {
	return o._statusCode
}

func (o *RankTypesGetSummariesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/RankTypes/Summary][%d] RankTypes_GetSummaries default %s", o._statusCode, payload)
}

func (o *RankTypesGetSummariesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/RankTypes/Summary][%d] RankTypes_GetSummaries default %s", o._statusCode, payload)
}

func (o *RankTypesGetSummariesDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *RankTypesGetSummariesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
