// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStepsGetParams creates a new StepsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStepsGetParams() *StepsGetParams {
	return &StepsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStepsGetParamsWithTimeout creates a new StepsGetParams object
// with the ability to set a timeout on a request.
func NewStepsGetParamsWithTimeout(timeout time.Duration) *StepsGetParams {
	return &StepsGetParams{
		timeout: timeout,
	}
}

// NewStepsGetParamsWithContext creates a new StepsGetParams object
// with the ability to set a context for a request.
func NewStepsGetParamsWithContext(ctx context.Context) *StepsGetParams {
	return &StepsGetParams{
		Context: ctx,
	}
}

// NewStepsGetParamsWithHTTPClient creates a new StepsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewStepsGetParamsWithHTTPClient(client *http.Client) *StepsGetParams {
	return &StepsGetParams{
		HTTPClient: client,
	}
}

/*
StepsGetParams contains all the parameters to send to the API endpoint

	for the steps get operation.

	Typically these are written to a http.Request.
*/
type StepsGetParams struct {

	// StepID.
	StepID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the steps get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StepsGetParams) WithDefaults() *StepsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the steps get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StepsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the steps get params
func (o *StepsGetParams) WithTimeout(timeout time.Duration) *StepsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the steps get params
func (o *StepsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the steps get params
func (o *StepsGetParams) WithContext(ctx context.Context) *StepsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the steps get params
func (o *StepsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the steps get params
func (o *StepsGetParams) WithHTTPClient(client *http.Client) *StepsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the steps get params
func (o *StepsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithStepID adds the stepID to the steps get params
func (o *StepsGetParams) WithStepID(stepID string) *StepsGetParams {
	o.SetStepID(stepID)
	return o
}

// SetStepID adds the stepId to the steps get params
func (o *StepsGetParams) SetStepID(stepID string) {
	o.StepID = stepID
}

// WriteToRequest writes these params to a swagger request
func (o *StepsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param stepId
	if err := r.SetPathParam("stepId", o.StepID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
