// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSurveyQuestionsGetParams creates a new SurveyQuestionsGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSurveyQuestionsGetParams() *SurveyQuestionsGetParams {
	return &SurveyQuestionsGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSurveyQuestionsGetParamsWithTimeout creates a new SurveyQuestionsGetParams object
// with the ability to set a timeout on a request.
func NewSurveyQuestionsGetParamsWithTimeout(timeout time.Duration) *SurveyQuestionsGetParams {
	return &SurveyQuestionsGetParams{
		timeout: timeout,
	}
}

// NewSurveyQuestionsGetParamsWithContext creates a new SurveyQuestionsGetParams object
// with the ability to set a context for a request.
func NewSurveyQuestionsGetParamsWithContext(ctx context.Context) *SurveyQuestionsGetParams {
	return &SurveyQuestionsGetParams{
		Context: ctx,
	}
}

// NewSurveyQuestionsGetParamsWithHTTPClient creates a new SurveyQuestionsGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewSurveyQuestionsGetParamsWithHTTPClient(client *http.Client) *SurveyQuestionsGetParams {
	return &SurveyQuestionsGetParams{
		HTTPClient: client,
	}
}

/*
SurveyQuestionsGetParams contains all the parameters to send to the API endpoint

	for the survey questions get operation.

	Typically these are written to a http.Request.
*/
type SurveyQuestionsGetParams struct {

	/* Filter.

	   Filter by user access (default: readwrite)
	*/
	Filter *string

	/* ID.

	   The id of the resource
	*/
	ID string

	/* MaintenanceMode.

	   Ignore control grouping (default: false)
	*/
	MaintenanceMode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the survey questions get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SurveyQuestionsGetParams) WithDefaults() *SurveyQuestionsGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the survey questions get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SurveyQuestionsGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the survey questions get params
func (o *SurveyQuestionsGetParams) WithTimeout(timeout time.Duration) *SurveyQuestionsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the survey questions get params
func (o *SurveyQuestionsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the survey questions get params
func (o *SurveyQuestionsGetParams) WithContext(ctx context.Context) *SurveyQuestionsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the survey questions get params
func (o *SurveyQuestionsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the survey questions get params
func (o *SurveyQuestionsGetParams) WithHTTPClient(client *http.Client) *SurveyQuestionsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the survey questions get params
func (o *SurveyQuestionsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the survey questions get params
func (o *SurveyQuestionsGetParams) WithFilter(filter *string) *SurveyQuestionsGetParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the survey questions get params
func (o *SurveyQuestionsGetParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithID adds the id to the survey questions get params
func (o *SurveyQuestionsGetParams) WithID(id string) *SurveyQuestionsGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the survey questions get params
func (o *SurveyQuestionsGetParams) SetID(id string) {
	o.ID = id
}

// WithMaintenanceMode adds the maintenanceMode to the survey questions get params
func (o *SurveyQuestionsGetParams) WithMaintenanceMode(maintenanceMode *string) *SurveyQuestionsGetParams {
	o.SetMaintenanceMode(maintenanceMode)
	return o
}

// SetMaintenanceMode adds the maintenanceMode to the survey questions get params
func (o *SurveyQuestionsGetParams) SetMaintenanceMode(maintenanceMode *string) {
	o.MaintenanceMode = maintenanceMode
}

// WriteToRequest writes these params to a swagger request
func (o *SurveyQuestionsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.MaintenanceMode != nil {

		// query param maintenanceMode
		var qrMaintenanceMode string

		if o.MaintenanceMode != nil {
			qrMaintenanceMode = *o.MaintenanceMode
		}
		qMaintenanceMode := qrMaintenanceMode
		if qMaintenanceMode != "" {

			if err := r.SetQueryParam("maintenanceMode", qMaintenanceMode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
