// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// TimeSlotsGetReader is a Reader for the TimeSlotsGet structure.
type TimeSlotsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TimeSlotsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTimeSlotsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTimeSlotsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTimeSlotsGetOK creates a TimeSlotsGetOK with default headers values
func NewTimeSlotsGetOK() *TimeSlotsGetOK {
	return &TimeSlotsGetOK{}
}

/*
TimeSlotsGetOK describes a response with status code 200, with default header values.

OK
*/
type TimeSlotsGetOK struct {
	Payload *models.TimeSlot
}

// IsSuccess returns true when this time slots get o k response has a 2xx status code
func (o *TimeSlotsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this time slots get o k response has a 3xx status code
func (o *TimeSlotsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this time slots get o k response has a 4xx status code
func (o *TimeSlotsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this time slots get o k response has a 5xx status code
func (o *TimeSlotsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this time slots get o k response a status code equal to that given
func (o *TimeSlotsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the time slots get o k response
func (o *TimeSlotsGetOK) Code() int {
	return 200
}

func (o *TimeSlotsGetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/TimeSlots/{id}][%d] timeSlotsGetOK %s", 200, payload)
}

func (o *TimeSlotsGetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/TimeSlots/{id}][%d] timeSlotsGetOK %s", 200, payload)
}

func (o *TimeSlotsGetOK) GetPayload() *models.TimeSlot {
	return o.Payload
}

func (o *TimeSlotsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimeSlot)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTimeSlotsGetDefault creates a TimeSlotsGetDefault with default headers values
func NewTimeSlotsGetDefault(code int) *TimeSlotsGetDefault {
	return &TimeSlotsGetDefault{
		_statusCode: code,
	}
}

/*
TimeSlotsGetDefault describes a response with status code -1, with default header values.

Error
*/
type TimeSlotsGetDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this time slots get default response has a 2xx status code
func (o *TimeSlotsGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this time slots get default response has a 3xx status code
func (o *TimeSlotsGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this time slots get default response has a 4xx status code
func (o *TimeSlotsGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this time slots get default response has a 5xx status code
func (o *TimeSlotsGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this time slots get default response a status code equal to that given
func (o *TimeSlotsGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the time slots get default response
func (o *TimeSlotsGetDefault) Code() int {
	return o._statusCode
}

func (o *TimeSlotsGetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/TimeSlots/{id}][%d] TimeSlots_Get default %s", o._statusCode, payload)
}

func (o *TimeSlotsGetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/TimeSlots/{id}][%d] TimeSlots_Get default %s", o._statusCode, payload)
}

func (o *TimeSlotsGetDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *TimeSlotsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
