// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// WorkerRolesGetSummariesReader is a Reader for the WorkerRolesGetSummaries structure.
type WorkerRolesGetSummariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WorkerRolesGetSummariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWorkerRolesGetSummariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWorkerRolesGetSummariesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWorkerRolesGetSummariesOK creates a WorkerRolesGetSummariesOK with default headers values
func NewWorkerRolesGetSummariesOK() *WorkerRolesGetSummariesOK {
	return &WorkerRolesGetSummariesOK{}
}

/*
WorkerRolesGetSummariesOK describes a response with status code 200, with default header values.

OK
*/
type WorkerRolesGetSummariesOK struct {
	Payload []*models.WorkerRoleSummary
}

// IsSuccess returns true when this worker roles get summaries o k response has a 2xx status code
func (o *WorkerRolesGetSummariesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this worker roles get summaries o k response has a 3xx status code
func (o *WorkerRolesGetSummariesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this worker roles get summaries o k response has a 4xx status code
func (o *WorkerRolesGetSummariesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this worker roles get summaries o k response has a 5xx status code
func (o *WorkerRolesGetSummariesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this worker roles get summaries o k response a status code equal to that given
func (o *WorkerRolesGetSummariesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the worker roles get summaries o k response
func (o *WorkerRolesGetSummariesOK) Code() int {
	return 200
}

func (o *WorkerRolesGetSummariesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/WorkerRoles/Summary][%d] workerRolesGetSummariesOK %s", 200, payload)
}

func (o *WorkerRolesGetSummariesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/WorkerRoles/Summary][%d] workerRolesGetSummariesOK %s", 200, payload)
}

func (o *WorkerRolesGetSummariesOK) GetPayload() []*models.WorkerRoleSummary {
	return o.Payload
}

func (o *WorkerRolesGetSummariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWorkerRolesGetSummariesDefault creates a WorkerRolesGetSummariesDefault with default headers values
func NewWorkerRolesGetSummariesDefault(code int) *WorkerRolesGetSummariesDefault {
	return &WorkerRolesGetSummariesDefault{
		_statusCode: code,
	}
}

/*
WorkerRolesGetSummariesDefault describes a response with status code -1, with default header values.

Error
*/
type WorkerRolesGetSummariesDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this worker roles get summaries default response has a 2xx status code
func (o *WorkerRolesGetSummariesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this worker roles get summaries default response has a 3xx status code
func (o *WorkerRolesGetSummariesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this worker roles get summaries default response has a 4xx status code
func (o *WorkerRolesGetSummariesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this worker roles get summaries default response has a 5xx status code
func (o *WorkerRolesGetSummariesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this worker roles get summaries default response a status code equal to that given
func (o *WorkerRolesGetSummariesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the worker roles get summaries default response
func (o *WorkerRolesGetSummariesDefault) Code() int {
	return o._statusCode
}

func (o *WorkerRolesGetSummariesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/WorkerRoles/Summary][%d] WorkerRoles_GetSummaries default %s", o._statusCode, payload)
}

func (o *WorkerRolesGetSummariesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /ReferenceData/WorkerRoles/Summary][%d] WorkerRoles_GetSummaries default %s", o._statusCode, payload)
}

func (o *WorkerRolesGetSummariesDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *WorkerRolesGetSummariesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
