// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewWorkerRolesGetParams creates a new WorkerRolesGetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewWorkerRolesGetParams() *WorkerRolesGetParams {
	return &WorkerRolesGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewWorkerRolesGetParamsWithTimeout creates a new WorkerRolesGetParams object
// with the ability to set a timeout on a request.
func NewWorkerRolesGetParamsWithTimeout(timeout time.Duration) *WorkerRolesGetParams {
	return &WorkerRolesGetParams{
		timeout: timeout,
	}
}

// NewWorkerRolesGetParamsWithContext creates a new WorkerRolesGetParams object
// with the ability to set a context for a request.
func NewWorkerRolesGetParamsWithContext(ctx context.Context) *WorkerRolesGetParams {
	return &WorkerRolesGetParams{
		Context: ctx,
	}
}

// NewWorkerRolesGetParamsWithHTTPClient creates a new WorkerRolesGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewWorkerRolesGetParamsWithHTTPClient(client *http.Client) *WorkerRolesGetParams {
	return &WorkerRolesGetParams{
		HTTPClient: client,
	}
}

/*
WorkerRolesGetParams contains all the parameters to send to the API endpoint

	for the worker roles get operation.

	Typically these are written to a http.Request.
*/
type WorkerRolesGetParams struct {

	/* Filter.

	   Filter by user access (default: readwrite)
	*/
	Filter *string

	// ID.
	ID string

	/* MaintenanceMode.

	   Ignore control grouping (default: false)
	*/
	MaintenanceMode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the worker roles get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkerRolesGetParams) WithDefaults() *WorkerRolesGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the worker roles get params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *WorkerRolesGetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the worker roles get params
func (o *WorkerRolesGetParams) WithTimeout(timeout time.Duration) *WorkerRolesGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the worker roles get params
func (o *WorkerRolesGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the worker roles get params
func (o *WorkerRolesGetParams) WithContext(ctx context.Context) *WorkerRolesGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the worker roles get params
func (o *WorkerRolesGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the worker roles get params
func (o *WorkerRolesGetParams) WithHTTPClient(client *http.Client) *WorkerRolesGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the worker roles get params
func (o *WorkerRolesGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilter adds the filter to the worker roles get params
func (o *WorkerRolesGetParams) WithFilter(filter *string) *WorkerRolesGetParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the worker roles get params
func (o *WorkerRolesGetParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WithID adds the id to the worker roles get params
func (o *WorkerRolesGetParams) WithID(id string) *WorkerRolesGetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the worker roles get params
func (o *WorkerRolesGetParams) SetID(id string) {
	o.ID = id
}

// WithMaintenanceMode adds the maintenanceMode to the worker roles get params
func (o *WorkerRolesGetParams) WithMaintenanceMode(maintenanceMode *string) *WorkerRolesGetParams {
	o.SetMaintenanceMode(maintenanceMode)
	return o
}

// SetMaintenanceMode adds the maintenanceMode to the worker roles get params
func (o *WorkerRolesGetParams) SetMaintenanceMode(maintenanceMode *string) {
	o.MaintenanceMode = maintenanceMode
}

// WriteToRequest writes these params to a swagger request
func (o *WorkerRolesGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Filter != nil {

		// query param filter
		var qrFilter string

		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {

			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.MaintenanceMode != nil {

		// query param maintenanceMode
		var qrMaintenanceMode string

		if o.MaintenanceMode != nil {
			qrMaintenanceMode = *o.MaintenanceMode
		}
		qMaintenanceMode := qrMaintenanceMode
		if qMaintenanceMode != "" {

			if err := r.SetQueryParam("maintenanceMode", qMaintenanceMode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
