// Code generated by go-swagger; DO NOT EDIT.

package g_e_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ZoneGroupsGetSummariesReader is a Reader for the ZoneGroupsGetSummaries structure.
type ZoneGroupsGetSummariesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ZoneGroupsGetSummariesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewZoneGroupsGetSummariesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /ReferenceData/ZoneGroups/Summary] ZoneGroups_GetSummaries", response, response.Code())
	}
}

// NewZoneGroupsGetSummariesOK creates a ZoneGroupsGetSummariesOK with default headers values
func NewZoneGroupsGetSummariesOK() *ZoneGroupsGetSummariesOK {
	return &ZoneGroupsGetSummariesOK{}
}

/*
ZoneGroupsGetSummariesOK describes a response with status code 200, with default header values.

OK
*/
type ZoneGroupsGetSummariesOK struct {
	Payload []*models.ZoneGroupSummary
}

// IsSuccess returns true when this zone groups get summaries o k response has a 2xx status code
func (o *ZoneGroupsGetSummariesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this zone groups get summaries o k response has a 3xx status code
func (o *ZoneGroupsGetSummariesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this zone groups get summaries o k response has a 4xx status code
func (o *ZoneGroupsGetSummariesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this zone groups get summaries o k response has a 5xx status code
func (o *ZoneGroupsGetSummariesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this zone groups get summaries o k response a status code equal to that given
func (o *ZoneGroupsGetSummariesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the zone groups get summaries o k response
func (o *ZoneGroupsGetSummariesOK) Code() int {
	return 200
}

func (o *ZoneGroupsGetSummariesOK) Error() string {
	return fmt.Sprintf("[GET /ReferenceData/ZoneGroups/Summary][%d] zoneGroupsGetSummariesOK  %+v", 200, o.Payload)
}

func (o *ZoneGroupsGetSummariesOK) String() string {
	return fmt.Sprintf("[GET /ReferenceData/ZoneGroups/Summary][%d] zoneGroupsGetSummariesOK  %+v", 200, o.Payload)
}

func (o *ZoneGroupsGetSummariesOK) GetPayload() []*models.ZoneGroupSummary {
	return o.Payload
}

func (o *ZoneGroupsGetSummariesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
