// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// AssociationTypesUpdateReader is a Reader for the AssociationTypesUpdate structure.
type AssociationTypesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssociationTypesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssociationTypesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewAssociationTypesUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAssociationTypesUpdateOK creates a AssociationTypesUpdateOK with default headers values
func NewAssociationTypesUpdateOK() *AssociationTypesUpdateOK {
	return &AssociationTypesUpdateOK{}
}

/*
AssociationTypesUpdateOK describes a response with status code 200, with default header values.

OK
*/
type AssociationTypesUpdateOK struct {
	Payload *models.AssociationType
}

// IsSuccess returns true when this association types update o k response has a 2xx status code
func (o *AssociationTypesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this association types update o k response has a 3xx status code
func (o *AssociationTypesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this association types update o k response has a 4xx status code
func (o *AssociationTypesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this association types update o k response has a 5xx status code
func (o *AssociationTypesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this association types update o k response a status code equal to that given
func (o *AssociationTypesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the association types update o k response
func (o *AssociationTypesUpdateOK) Code() int {
	return 200
}

func (o *AssociationTypesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/AssociationTypes/{id}][%d] associationTypesUpdateOK %s", 200, payload)
}

func (o *AssociationTypesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/AssociationTypes/{id}][%d] associationTypesUpdateOK %s", 200, payload)
}

func (o *AssociationTypesUpdateOK) GetPayload() *models.AssociationType {
	return o.Payload
}

func (o *AssociationTypesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AssociationType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssociationTypesUpdateDefault creates a AssociationTypesUpdateDefault with default headers values
func NewAssociationTypesUpdateDefault(code int) *AssociationTypesUpdateDefault {
	return &AssociationTypesUpdateDefault{
		_statusCode: code,
	}
}

/*
AssociationTypesUpdateDefault describes a response with status code -1, with default header values.

Error
*/
type AssociationTypesUpdateDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this association types update default response has a 2xx status code
func (o *AssociationTypesUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this association types update default response has a 3xx status code
func (o *AssociationTypesUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this association types update default response has a 4xx status code
func (o *AssociationTypesUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this association types update default response has a 5xx status code
func (o *AssociationTypesUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this association types update default response a status code equal to that given
func (o *AssociationTypesUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the association types update default response
func (o *AssociationTypesUpdateDefault) Code() int {
	return o._statusCode
}

func (o *AssociationTypesUpdateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/AssociationTypes/{id}][%d] AssociationTypes_Update default %s", o._statusCode, payload)
}

func (o *AssociationTypesUpdateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/AssociationTypes/{id}][%d] AssociationTypes_Update default %s", o._statusCode, payload)
}

func (o *AssociationTypesUpdateDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *AssociationTypesUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
