// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// AttributesUpdateReader is a Reader for the AttributesUpdate structure.
type AttributesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AttributesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAttributesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /CRM/Attributes/{attributeId}] Attributes_Update", response, response.Code())
	}
}

// NewAttributesUpdateOK creates a AttributesUpdateOK with default headers values
func NewAttributesUpdateOK() *AttributesUpdateOK {
	return &AttributesUpdateOK{}
}

/*
AttributesUpdateOK describes a response with status code 200, with default header values.

OK
*/
type AttributesUpdateOK struct {
	Payload *models.Attribute
}

// IsSuccess returns true when this attributes update o k response has a 2xx status code
func (o *AttributesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this attributes update o k response has a 3xx status code
func (o *AttributesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this attributes update o k response has a 4xx status code
func (o *AttributesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this attributes update o k response has a 5xx status code
func (o *AttributesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this attributes update o k response a status code equal to that given
func (o *AttributesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the attributes update o k response
func (o *AttributesUpdateOK) Code() int {
	return 200
}

func (o *AttributesUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /CRM/Attributes/{attributeId}][%d] attributesUpdateOK  %+v", 200, o.Payload)
}

func (o *AttributesUpdateOK) String() string {
	return fmt.Sprintf("[PUT /CRM/Attributes/{attributeId}][%d] attributesUpdateOK  %+v", 200, o.Payload)
}

func (o *AttributesUpdateOK) GetPayload() *models.Attribute {
	return o.Payload
}

func (o *AttributesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attribute)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
