// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// BillingSchedulesUpdateReader is a Reader for the BillingSchedulesUpdate structure.
type BillingSchedulesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BillingSchedulesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBillingSchedulesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /ReferenceData/BillingSchedules/{id}] BillingSchedules_Update", response, response.Code())
	}
}

// NewBillingSchedulesUpdateOK creates a BillingSchedulesUpdateOK with default headers values
func NewBillingSchedulesUpdateOK() *BillingSchedulesUpdateOK {
	return &BillingSchedulesUpdateOK{}
}

/*
BillingSchedulesUpdateOK describes a response with status code 200, with default header values.

OK
*/
type BillingSchedulesUpdateOK struct {
	Payload *models.BillingSchedule
}

// IsSuccess returns true when this billing schedules update o k response has a 2xx status code
func (o *BillingSchedulesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this billing schedules update o k response has a 3xx status code
func (o *BillingSchedulesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this billing schedules update o k response has a 4xx status code
func (o *BillingSchedulesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this billing schedules update o k response has a 5xx status code
func (o *BillingSchedulesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this billing schedules update o k response a status code equal to that given
func (o *BillingSchedulesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the billing schedules update o k response
func (o *BillingSchedulesUpdateOK) Code() int {
	return 200
}

func (o *BillingSchedulesUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /ReferenceData/BillingSchedules/{id}][%d] billingSchedulesUpdateOK  %+v", 200, o.Payload)
}

func (o *BillingSchedulesUpdateOK) String() string {
	return fmt.Sprintf("[PUT /ReferenceData/BillingSchedules/{id}][%d] billingSchedulesUpdateOK  %+v", 200, o.Payload)
}

func (o *BillingSchedulesUpdateOK) GetPayload() *models.BillingSchedule {
	return o.Payload
}

func (o *BillingSchedulesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BillingSchedule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
