// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// CampaignFundsUpdateReader is a Reader for the CampaignFundsUpdate structure.
type CampaignFundsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CampaignFundsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCampaignFundsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /Finance/CampaignFunds/{campaignFundId}] CampaignFunds_Update", response, response.Code())
	}
}

// NewCampaignFundsUpdateOK creates a CampaignFundsUpdateOK with default headers values
func NewCampaignFundsUpdateOK() *CampaignFundsUpdateOK {
	return &CampaignFundsUpdateOK{}
}

/*
CampaignFundsUpdateOK describes a response with status code 200, with default header values.

OK
*/
type CampaignFundsUpdateOK struct {
	Payload *models.CampaignFund
}

// IsSuccess returns true when this campaign funds update o k response has a 2xx status code
func (o *CampaignFundsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this campaign funds update o k response has a 3xx status code
func (o *CampaignFundsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this campaign funds update o k response has a 4xx status code
func (o *CampaignFundsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this campaign funds update o k response has a 5xx status code
func (o *CampaignFundsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this campaign funds update o k response a status code equal to that given
func (o *CampaignFundsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the campaign funds update o k response
func (o *CampaignFundsUpdateOK) Code() int {
	return 200
}

func (o *CampaignFundsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /Finance/CampaignFunds/{campaignFundId}][%d] campaignFundsUpdateOK  %+v", 200, o.Payload)
}

func (o *CampaignFundsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /Finance/CampaignFunds/{campaignFundId}][%d] campaignFundsUpdateOK  %+v", 200, o.Payload)
}

func (o *CampaignFundsUpdateOK) GetPayload() *models.CampaignFund {
	return o.Payload
}

func (o *CampaignFundsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CampaignFund)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
