// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CartUpdateSubLineItemRecipientReader is a Reader for the CartUpdateSubLineItemRecipient structure.
type CartUpdateSubLineItemRecipientReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CartUpdateSubLineItemRecipientReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCartUpdateSubLineItemRecipientNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /Web/Cart/{sessionKey}/SubLineItems/{subLineItemId}/Recipient] Cart_UpdateSubLineItemRecipient", response, response.Code())
	}
}

// NewCartUpdateSubLineItemRecipientNoContent creates a CartUpdateSubLineItemRecipientNoContent with default headers values
func NewCartUpdateSubLineItemRecipientNoContent() *CartUpdateSubLineItemRecipientNoContent {
	return &CartUpdateSubLineItemRecipientNoContent{}
}

/*
CartUpdateSubLineItemRecipientNoContent describes a response with status code 204, with default header values.

No Content
*/
type CartUpdateSubLineItemRecipientNoContent struct {
}

// IsSuccess returns true when this cart update sub line item recipient no content response has a 2xx status code
func (o *CartUpdateSubLineItemRecipientNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cart update sub line item recipient no content response has a 3xx status code
func (o *CartUpdateSubLineItemRecipientNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cart update sub line item recipient no content response has a 4xx status code
func (o *CartUpdateSubLineItemRecipientNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this cart update sub line item recipient no content response has a 5xx status code
func (o *CartUpdateSubLineItemRecipientNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this cart update sub line item recipient no content response a status code equal to that given
func (o *CartUpdateSubLineItemRecipientNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the cart update sub line item recipient no content response
func (o *CartUpdateSubLineItemRecipientNoContent) Code() int {
	return 204
}

func (o *CartUpdateSubLineItemRecipientNoContent) Error() string {
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/SubLineItems/{subLineItemId}/Recipient][%d] cartUpdateSubLineItemRecipientNoContent ", 204)
}

func (o *CartUpdateSubLineItemRecipientNoContent) String() string {
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/SubLineItems/{subLineItemId}/Recipient][%d] cartUpdateSubLineItemRecipientNoContent ", 204)
}

func (o *CartUpdateSubLineItemRecipientNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
