// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// CartUpdateContributionCustomDataReader is a Reader for the CartUpdateContributionCustomData structure.
type CartUpdateContributionCustomDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CartUpdateContributionCustomDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCartUpdateContributionCustomDataNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCartUpdateContributionCustomDataDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCartUpdateContributionCustomDataNoContent creates a CartUpdateContributionCustomDataNoContent with default headers values
func NewCartUpdateContributionCustomDataNoContent() *CartUpdateContributionCustomDataNoContent {
	return &CartUpdateContributionCustomDataNoContent{}
}

/*
CartUpdateContributionCustomDataNoContent describes a response with status code 204, with default header values.

No Content
*/
type CartUpdateContributionCustomDataNoContent struct {
}

// IsSuccess returns true when this cart update contribution custom data no content response has a 2xx status code
func (o *CartUpdateContributionCustomDataNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cart update contribution custom data no content response has a 3xx status code
func (o *CartUpdateContributionCustomDataNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cart update contribution custom data no content response has a 4xx status code
func (o *CartUpdateContributionCustomDataNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this cart update contribution custom data no content response has a 5xx status code
func (o *CartUpdateContributionCustomDataNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this cart update contribution custom data no content response a status code equal to that given
func (o *CartUpdateContributionCustomDataNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the cart update contribution custom data no content response
func (o *CartUpdateContributionCustomDataNoContent) Code() int {
	return 204
}

func (o *CartUpdateContributionCustomDataNoContent) Error() string {
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/Contributions/{lineItemId}/CustomData/{customId}][%d] cartUpdateContributionCustomDataNoContent", 204)
}

func (o *CartUpdateContributionCustomDataNoContent) String() string {
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/Contributions/{lineItemId}/CustomData/{customId}][%d] cartUpdateContributionCustomDataNoContent", 204)
}

func (o *CartUpdateContributionCustomDataNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCartUpdateContributionCustomDataDefault creates a CartUpdateContributionCustomDataDefault with default headers values
func NewCartUpdateContributionCustomDataDefault(code int) *CartUpdateContributionCustomDataDefault {
	return &CartUpdateContributionCustomDataDefault{
		_statusCode: code,
	}
}

/*
CartUpdateContributionCustomDataDefault describes a response with status code -1, with default header values.

Error
*/
type CartUpdateContributionCustomDataDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this cart update contribution custom data default response has a 2xx status code
func (o *CartUpdateContributionCustomDataDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this cart update contribution custom data default response has a 3xx status code
func (o *CartUpdateContributionCustomDataDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this cart update contribution custom data default response has a 4xx status code
func (o *CartUpdateContributionCustomDataDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this cart update contribution custom data default response has a 5xx status code
func (o *CartUpdateContributionCustomDataDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this cart update contribution custom data default response a status code equal to that given
func (o *CartUpdateContributionCustomDataDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the cart update contribution custom data default response
func (o *CartUpdateContributionCustomDataDefault) Code() int {
	return o._statusCode
}

func (o *CartUpdateContributionCustomDataDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/Contributions/{lineItemId}/CustomData/{customId}][%d] Cart_UpdateContributionCustomData default %s", o._statusCode, payload)
}

func (o *CartUpdateContributionCustomDataDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /Web/Cart/{sessionKey}/Contributions/{lineItemId}/CustomData/{customId}][%d] Cart_UpdateContributionCustomData default %s", o._statusCode, payload)
}

func (o *CartUpdateContributionCustomDataDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *CartUpdateContributionCustomDataDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
