// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ConstituenciesUpdateReader is a Reader for the ConstituenciesUpdate structure.
type ConstituenciesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConstituenciesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConstituenciesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewConstituenciesUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewConstituenciesUpdateOK creates a ConstituenciesUpdateOK with default headers values
func NewConstituenciesUpdateOK() *ConstituenciesUpdateOK {
	return &ConstituenciesUpdateOK{}
}

/*
ConstituenciesUpdateOK describes a response with status code 200, with default header values.

OK
*/
type ConstituenciesUpdateOK struct {
	Payload *models.Constituency
}

// IsSuccess returns true when this constituencies update o k response has a 2xx status code
func (o *ConstituenciesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this constituencies update o k response has a 3xx status code
func (o *ConstituenciesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this constituencies update o k response has a 4xx status code
func (o *ConstituenciesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this constituencies update o k response has a 5xx status code
func (o *ConstituenciesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this constituencies update o k response a status code equal to that given
func (o *ConstituenciesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the constituencies update o k response
func (o *ConstituenciesUpdateOK) Code() int {
	return 200
}

func (o *ConstituenciesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /CRM/Constituencies/{constituencyId}][%d] constituenciesUpdateOK %s", 200, payload)
}

func (o *ConstituenciesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /CRM/Constituencies/{constituencyId}][%d] constituenciesUpdateOK %s", 200, payload)
}

func (o *ConstituenciesUpdateOK) GetPayload() *models.Constituency {
	return o.Payload
}

func (o *ConstituenciesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Constituency)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConstituenciesUpdateDefault creates a ConstituenciesUpdateDefault with default headers values
func NewConstituenciesUpdateDefault(code int) *ConstituenciesUpdateDefault {
	return &ConstituenciesUpdateDefault{
		_statusCode: code,
	}
}

/*
ConstituenciesUpdateDefault describes a response with status code -1, with default header values.

Error
*/
type ConstituenciesUpdateDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this constituencies update default response has a 2xx status code
func (o *ConstituenciesUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this constituencies update default response has a 3xx status code
func (o *ConstituenciesUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this constituencies update default response has a 4xx status code
func (o *ConstituenciesUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this constituencies update default response has a 5xx status code
func (o *ConstituenciesUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this constituencies update default response a status code equal to that given
func (o *ConstituenciesUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the constituencies update default response
func (o *ConstituenciesUpdateDefault) Code() int {
	return o._statusCode
}

func (o *ConstituenciesUpdateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /CRM/Constituencies/{constituencyId}][%d] Constituencies_Update default %s", o._statusCode, payload)
}

func (o *ConstituenciesUpdateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /CRM/Constituencies/{constituencyId}][%d] Constituencies_Update default %s", o._statusCode, payload)
}

func (o *ConstituenciesUpdateDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *ConstituenciesUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
