// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// NewContactPermissionsUpdateParams creates a new ContactPermissionsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewContactPermissionsUpdateParams() *ContactPermissionsUpdateParams {
	return &ContactPermissionsUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewContactPermissionsUpdateParamsWithTimeout creates a new ContactPermissionsUpdateParams object
// with the ability to set a timeout on a request.
func NewContactPermissionsUpdateParamsWithTimeout(timeout time.Duration) *ContactPermissionsUpdateParams {
	return &ContactPermissionsUpdateParams{
		timeout: timeout,
	}
}

// NewContactPermissionsUpdateParamsWithContext creates a new ContactPermissionsUpdateParams object
// with the ability to set a context for a request.
func NewContactPermissionsUpdateParamsWithContext(ctx context.Context) *ContactPermissionsUpdateParams {
	return &ContactPermissionsUpdateParams{
		Context: ctx,
	}
}

// NewContactPermissionsUpdateParamsWithHTTPClient creates a new ContactPermissionsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewContactPermissionsUpdateParamsWithHTTPClient(client *http.Client) *ContactPermissionsUpdateParams {
	return &ContactPermissionsUpdateParams{
		HTTPClient: client,
	}
}

/*
ContactPermissionsUpdateParams contains all the parameters to send to the API endpoint

	for the contact permissions update operation.

	Typically these are written to a http.Request.
*/
type ContactPermissionsUpdateParams struct {

	// ContactPermission.
	ContactPermission *models.ContactPermission

	// ContactPermissionID.
	ContactPermissionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the contact permissions update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContactPermissionsUpdateParams) WithDefaults() *ContactPermissionsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the contact permissions update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ContactPermissionsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the contact permissions update params
func (o *ContactPermissionsUpdateParams) WithTimeout(timeout time.Duration) *ContactPermissionsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the contact permissions update params
func (o *ContactPermissionsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the contact permissions update params
func (o *ContactPermissionsUpdateParams) WithContext(ctx context.Context) *ContactPermissionsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the contact permissions update params
func (o *ContactPermissionsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the contact permissions update params
func (o *ContactPermissionsUpdateParams) WithHTTPClient(client *http.Client) *ContactPermissionsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the contact permissions update params
func (o *ContactPermissionsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContactPermission adds the contactPermission to the contact permissions update params
func (o *ContactPermissionsUpdateParams) WithContactPermission(contactPermission *models.ContactPermission) *ContactPermissionsUpdateParams {
	o.SetContactPermission(contactPermission)
	return o
}

// SetContactPermission adds the contactPermission to the contact permissions update params
func (o *ContactPermissionsUpdateParams) SetContactPermission(contactPermission *models.ContactPermission) {
	o.ContactPermission = contactPermission
}

// WithContactPermissionID adds the contactPermissionID to the contact permissions update params
func (o *ContactPermissionsUpdateParams) WithContactPermissionID(contactPermissionID string) *ContactPermissionsUpdateParams {
	o.SetContactPermissionID(contactPermissionID)
	return o
}

// SetContactPermissionID adds the contactPermissionId to the contact permissions update params
func (o *ContactPermissionsUpdateParams) SetContactPermissionID(contactPermissionID string) {
	o.ContactPermissionID = contactPermissionID
}

// WriteToRequest writes these params to a swagger request
func (o *ContactPermissionsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ContactPermission != nil {
		if err := r.SetBodyParam(o.ContactPermission); err != nil {
			return err
		}
	}

	// path param contactPermissionId
	if err := r.SetPathParam("contactPermissionId", o.ContactPermissionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
