// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PaymentMethodsUpdateReader is a Reader for the PaymentMethodsUpdate structure.
type PaymentMethodsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PaymentMethodsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPaymentMethodsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPaymentMethodsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPaymentMethodsUpdateOK creates a PaymentMethodsUpdateOK with default headers values
func NewPaymentMethodsUpdateOK() *PaymentMethodsUpdateOK {
	return &PaymentMethodsUpdateOK{}
}

/*
PaymentMethodsUpdateOK describes a response with status code 200, with default header values.

OK
*/
type PaymentMethodsUpdateOK struct {
	Payload *models.PaymentMethod
}

// IsSuccess returns true when this payment methods update o k response has a 2xx status code
func (o *PaymentMethodsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this payment methods update o k response has a 3xx status code
func (o *PaymentMethodsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this payment methods update o k response has a 4xx status code
func (o *PaymentMethodsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this payment methods update o k response has a 5xx status code
func (o *PaymentMethodsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this payment methods update o k response a status code equal to that given
func (o *PaymentMethodsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the payment methods update o k response
func (o *PaymentMethodsUpdateOK) Code() int {
	return 200
}

func (o *PaymentMethodsUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] paymentMethodsUpdateOK %s", 200, payload)
}

func (o *PaymentMethodsUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] paymentMethodsUpdateOK %s", 200, payload)
}

func (o *PaymentMethodsUpdateOK) GetPayload() *models.PaymentMethod {
	return o.Payload
}

func (o *PaymentMethodsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentMethod)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPaymentMethodsUpdateDefault creates a PaymentMethodsUpdateDefault with default headers values
func NewPaymentMethodsUpdateDefault(code int) *PaymentMethodsUpdateDefault {
	return &PaymentMethodsUpdateDefault{
		_statusCode: code,
	}
}

/*
PaymentMethodsUpdateDefault describes a response with status code -1, with default header values.

Error
*/
type PaymentMethodsUpdateDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this payment methods update default response has a 2xx status code
func (o *PaymentMethodsUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this payment methods update default response has a 3xx status code
func (o *PaymentMethodsUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this payment methods update default response has a 4xx status code
func (o *PaymentMethodsUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this payment methods update default response has a 5xx status code
func (o *PaymentMethodsUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this payment methods update default response a status code equal to that given
func (o *PaymentMethodsUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the payment methods update default response
func (o *PaymentMethodsUpdateDefault) Code() int {
	return o._statusCode
}

func (o *PaymentMethodsUpdateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] PaymentMethods_Update default %s", o._statusCode, payload)
}

func (o *PaymentMethodsUpdateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] PaymentMethods_Update default %s", o._statusCode, payload)
}

func (o *PaymentMethodsUpdateDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *PaymentMethodsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
