// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// PaymentMethodsUpdateReader is a Reader for the PaymentMethodsUpdate structure.
type PaymentMethodsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PaymentMethodsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPaymentMethodsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PUT /TXN/PaymentMethods/{paymentMethodId}] PaymentMethods_Update", response, response.Code())
	}
}

// NewPaymentMethodsUpdateOK creates a PaymentMethodsUpdateOK with default headers values
func NewPaymentMethodsUpdateOK() *PaymentMethodsUpdateOK {
	return &PaymentMethodsUpdateOK{}
}

/*
PaymentMethodsUpdateOK describes a response with status code 200, with default header values.

OK
*/
type PaymentMethodsUpdateOK struct {
	Payload *models.PaymentMethod
}

// IsSuccess returns true when this payment methods update o k response has a 2xx status code
func (o *PaymentMethodsUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this payment methods update o k response has a 3xx status code
func (o *PaymentMethodsUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this payment methods update o k response has a 4xx status code
func (o *PaymentMethodsUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this payment methods update o k response has a 5xx status code
func (o *PaymentMethodsUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this payment methods update o k response a status code equal to that given
func (o *PaymentMethodsUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the payment methods update o k response
func (o *PaymentMethodsUpdateOK) Code() int {
	return 200
}

func (o *PaymentMethodsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] paymentMethodsUpdateOK  %+v", 200, o.Payload)
}

func (o *PaymentMethodsUpdateOK) String() string {
	return fmt.Sprintf("[PUT /TXN/PaymentMethods/{paymentMethodId}][%d] paymentMethodsUpdateOK  %+v", 200, o.Payload)
}

func (o *PaymentMethodsUpdateOK) GetPayload() *models.PaymentMethod {
	return o.Payload
}

func (o *PaymentMethodsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaymentMethod)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
