// Code generated by go-swagger; DO NOT EDIT.

package p_u_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// TheatersUpdateReader is a Reader for the TheatersUpdate structure.
type TheatersUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TheatersUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTheatersUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTheatersUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTheatersUpdateOK creates a TheatersUpdateOK with default headers values
func NewTheatersUpdateOK() *TheatersUpdateOK {
	return &TheatersUpdateOK{}
}

/*
TheatersUpdateOK describes a response with status code 200, with default header values.

OK
*/
type TheatersUpdateOK struct {
	Payload *models.Theater
}

// IsSuccess returns true when this theaters update o k response has a 2xx status code
func (o *TheatersUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this theaters update o k response has a 3xx status code
func (o *TheatersUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this theaters update o k response has a 4xx status code
func (o *TheatersUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this theaters update o k response has a 5xx status code
func (o *TheatersUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this theaters update o k response a status code equal to that given
func (o *TheatersUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the theaters update o k response
func (o *TheatersUpdateOK) Code() int {
	return 200
}

func (o *TheatersUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/Theaters/{id}][%d] theatersUpdateOK %s", 200, payload)
}

func (o *TheatersUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/Theaters/{id}][%d] theatersUpdateOK %s", 200, payload)
}

func (o *TheatersUpdateOK) GetPayload() *models.Theater {
	return o.Payload
}

func (o *TheatersUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Theater)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTheatersUpdateDefault creates a TheatersUpdateDefault with default headers values
func NewTheatersUpdateDefault(code int) *TheatersUpdateDefault {
	return &TheatersUpdateDefault{
		_statusCode: code,
	}
}

/*
TheatersUpdateDefault describes a response with status code -1, with default header values.

Error
*/
type TheatersUpdateDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this theaters update default response has a 2xx status code
func (o *TheatersUpdateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this theaters update default response has a 3xx status code
func (o *TheatersUpdateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this theaters update default response has a 4xx status code
func (o *TheatersUpdateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this theaters update default response has a 5xx status code
func (o *TheatersUpdateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this theaters update default response a status code equal to that given
func (o *TheatersUpdateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the theaters update default response
func (o *TheatersUpdateDefault) Code() int {
	return o._statusCode
}

func (o *TheatersUpdateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/Theaters/{id}][%d] Theaters_Update default %s", o._statusCode, payload)
}

func (o *TheatersUpdateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PUT /ReferenceData/Theaters/{id}][%d] Theaters_Update default %s", o._statusCode, payload)
}

func (o *TheatersUpdateDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *TheatersUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
