// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// CardReaderTypesCreateReader is a Reader for the CardReaderTypesCreate structure.
type CardReaderTypesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CardReaderTypesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCardReaderTypesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /ReferenceData/CardReaderTypes] CardReaderTypes_Create", response, response.Code())
	}
}

// NewCardReaderTypesCreateOK creates a CardReaderTypesCreateOK with default headers values
func NewCardReaderTypesCreateOK() *CardReaderTypesCreateOK {
	return &CardReaderTypesCreateOK{}
}

/*
CardReaderTypesCreateOK describes a response with status code 200, with default header values.

OK
*/
type CardReaderTypesCreateOK struct {
	Payload *models.CardReaderType
}

// IsSuccess returns true when this card reader types create o k response has a 2xx status code
func (o *CardReaderTypesCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this card reader types create o k response has a 3xx status code
func (o *CardReaderTypesCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this card reader types create o k response has a 4xx status code
func (o *CardReaderTypesCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this card reader types create o k response has a 5xx status code
func (o *CardReaderTypesCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this card reader types create o k response a status code equal to that given
func (o *CardReaderTypesCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the card reader types create o k response
func (o *CardReaderTypesCreateOK) Code() int {
	return 200
}

func (o *CardReaderTypesCreateOK) Error() string {
	return fmt.Sprintf("[POST /ReferenceData/CardReaderTypes][%d] cardReaderTypesCreateOK  %+v", 200, o.Payload)
}

func (o *CardReaderTypesCreateOK) String() string {
	return fmt.Sprintf("[POST /ReferenceData/CardReaderTypes][%d] cardReaderTypesCreateOK  %+v", 200, o.Payload)
}

func (o *CardReaderTypesCreateOK) GetPayload() *models.CardReaderType {
	return o.Payload
}

func (o *CardReaderTypesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CardReaderType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
