// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CartValidateLimitsReader is a Reader for the CartValidateLimits structure.
type CartValidateLimitsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CartValidateLimitsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewCartValidateLimitsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /Web/Cart/{sessionKey}/ValidateLimits] Cart_ValidateLimits", response, response.Code())
	}
}

// NewCartValidateLimitsNoContent creates a CartValidateLimitsNoContent with default headers values
func NewCartValidateLimitsNoContent() *CartValidateLimitsNoContent {
	return &CartValidateLimitsNoContent{}
}

/*
CartValidateLimitsNoContent describes a response with status code 204, with default header values.

No Content
*/
type CartValidateLimitsNoContent struct {
}

// IsSuccess returns true when this cart validate limits no content response has a 2xx status code
func (o *CartValidateLimitsNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this cart validate limits no content response has a 3xx status code
func (o *CartValidateLimitsNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this cart validate limits no content response has a 4xx status code
func (o *CartValidateLimitsNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this cart validate limits no content response has a 5xx status code
func (o *CartValidateLimitsNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this cart validate limits no content response a status code equal to that given
func (o *CartValidateLimitsNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the cart validate limits no content response
func (o *CartValidateLimitsNoContent) Code() int {
	return 204
}

func (o *CartValidateLimitsNoContent) Error() string {
	return fmt.Sprintf("[POST /Web/Cart/{sessionKey}/ValidateLimits][%d] cartValidateLimitsNoContent ", 204)
}

func (o *CartValidateLimitsNoContent) String() string {
	return fmt.Sprintf("[POST /Web/Cart/{sessionKey}/ValidateLimits][%d] cartValidateLimitsNoContent ", 204)
}

func (o *CartValidateLimitsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
