// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// NewConstituentsCreateConstituentUsingSnapshotParams creates a new ConstituentsCreateConstituentUsingSnapshotParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConstituentsCreateConstituentUsingSnapshotParams() *ConstituentsCreateConstituentUsingSnapshotParams {
	return &ConstituentsCreateConstituentUsingSnapshotParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConstituentsCreateConstituentUsingSnapshotParamsWithTimeout creates a new ConstituentsCreateConstituentUsingSnapshotParams object
// with the ability to set a timeout on a request.
func NewConstituentsCreateConstituentUsingSnapshotParamsWithTimeout(timeout time.Duration) *ConstituentsCreateConstituentUsingSnapshotParams {
	return &ConstituentsCreateConstituentUsingSnapshotParams{
		timeout: timeout,
	}
}

// NewConstituentsCreateConstituentUsingSnapshotParamsWithContext creates a new ConstituentsCreateConstituentUsingSnapshotParams object
// with the ability to set a context for a request.
func NewConstituentsCreateConstituentUsingSnapshotParamsWithContext(ctx context.Context) *ConstituentsCreateConstituentUsingSnapshotParams {
	return &ConstituentsCreateConstituentUsingSnapshotParams{
		Context: ctx,
	}
}

// NewConstituentsCreateConstituentUsingSnapshotParamsWithHTTPClient creates a new ConstituentsCreateConstituentUsingSnapshotParams object
// with the ability to set a custom HTTPClient for a request.
func NewConstituentsCreateConstituentUsingSnapshotParamsWithHTTPClient(client *http.Client) *ConstituentsCreateConstituentUsingSnapshotParams {
	return &ConstituentsCreateConstituentUsingSnapshotParams{
		HTTPClient: client,
	}
}

/*
ConstituentsCreateConstituentUsingSnapshotParams contains all the parameters to send to the API endpoint

	for the constituents create constituent using snapshot operation.

	Typically these are written to a http.Request.
*/
type ConstituentsCreateConstituentUsingSnapshotParams struct {

	// ConstituentSnapshot.
	ConstituentSnapshot *models.ConstituentSnapshot

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the constituents create constituent using snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WithDefaults() *ConstituentsCreateConstituentUsingSnapshotParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the constituents create constituent using snapshot params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConstituentsCreateConstituentUsingSnapshotParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WithTimeout(timeout time.Duration) *ConstituentsCreateConstituentUsingSnapshotParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WithContext(ctx context.Context) *ConstituentsCreateConstituentUsingSnapshotParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WithHTTPClient(client *http.Client) *ConstituentsCreateConstituentUsingSnapshotParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConstituentSnapshot adds the constituentSnapshot to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WithConstituentSnapshot(constituentSnapshot *models.ConstituentSnapshot) *ConstituentsCreateConstituentUsingSnapshotParams {
	o.SetConstituentSnapshot(constituentSnapshot)
	return o
}

// SetConstituentSnapshot adds the constituentSnapshot to the constituents create constituent using snapshot params
func (o *ConstituentsCreateConstituentUsingSnapshotParams) SetConstituentSnapshot(constituentSnapshot *models.ConstituentSnapshot) {
	o.ConstituentSnapshot = constituentSnapshot
}

// WriteToRequest writes these params to a swagger request
func (o *ConstituentsCreateConstituentUsingSnapshotParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ConstituentSnapshot != nil {
		if err := r.SetBodyParam(o.ConstituentSnapshot); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
