// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ContactPermissionTypesCreateReader is a Reader for the ContactPermissionTypesCreate structure.
type ContactPermissionTypesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ContactPermissionTypesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewContactPermissionTypesCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /ReferenceData/ContactPermissionTypes] ContactPermissionTypes_Create", response, response.Code())
	}
}

// NewContactPermissionTypesCreateOK creates a ContactPermissionTypesCreateOK with default headers values
func NewContactPermissionTypesCreateOK() *ContactPermissionTypesCreateOK {
	return &ContactPermissionTypesCreateOK{}
}

/*
ContactPermissionTypesCreateOK describes a response with status code 200, with default header values.

OK
*/
type ContactPermissionTypesCreateOK struct {
	Payload *models.ContactPermissionType
}

// IsSuccess returns true when this contact permission types create o k response has a 2xx status code
func (o *ContactPermissionTypesCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this contact permission types create o k response has a 3xx status code
func (o *ContactPermissionTypesCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this contact permission types create o k response has a 4xx status code
func (o *ContactPermissionTypesCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this contact permission types create o k response has a 5xx status code
func (o *ContactPermissionTypesCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this contact permission types create o k response a status code equal to that given
func (o *ContactPermissionTypesCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the contact permission types create o k response
func (o *ContactPermissionTypesCreateOK) Code() int {
	return 200
}

func (o *ContactPermissionTypesCreateOK) Error() string {
	return fmt.Sprintf("[POST /ReferenceData/ContactPermissionTypes][%d] contactPermissionTypesCreateOK  %+v", 200, o.Payload)
}

func (o *ContactPermissionTypesCreateOK) String() string {
	return fmt.Sprintf("[POST /ReferenceData/ContactPermissionTypes][%d] contactPermissionTypesCreateOK  %+v", 200, o.Payload)
}

func (o *ContactPermissionTypesCreateOK) GetPayload() *models.ContactPermissionType {
	return o.Payload
}

func (o *ContactPermissionTypesCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ContactPermissionType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
