// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CustomExecuteLocalProcedureReader is a Reader for the CustomExecuteLocalProcedure structure.
type CustomExecuteLocalProcedureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomExecuteLocalProcedureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCustomExecuteLocalProcedureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /Custom/Execute] Custom_ExecuteLocalProcedure", response, response.Code())
	}
}

// NewCustomExecuteLocalProcedureOK creates a CustomExecuteLocalProcedureOK with default headers values
func NewCustomExecuteLocalProcedureOK() *CustomExecuteLocalProcedureOK {
	return &CustomExecuteLocalProcedureOK{}
}

/*
CustomExecuteLocalProcedureOK describes a response with status code 200, with default header values.

OK
*/
type CustomExecuteLocalProcedureOK struct {
	Payload interface{}
}

// IsSuccess returns true when this custom execute local procedure o k response has a 2xx status code
func (o *CustomExecuteLocalProcedureOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this custom execute local procedure o k response has a 3xx status code
func (o *CustomExecuteLocalProcedureOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this custom execute local procedure o k response has a 4xx status code
func (o *CustomExecuteLocalProcedureOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this custom execute local procedure o k response has a 5xx status code
func (o *CustomExecuteLocalProcedureOK) IsServerError() bool {
	return false
}

// IsCode returns true when this custom execute local procedure o k response a status code equal to that given
func (o *CustomExecuteLocalProcedureOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the custom execute local procedure o k response
func (o *CustomExecuteLocalProcedureOK) Code() int {
	return 200
}

func (o *CustomExecuteLocalProcedureOK) Error() string {
	return fmt.Sprintf("[POST /Custom/Execute][%d] customExecuteLocalProcedureOK  %+v", 200, o.Payload)
}

func (o *CustomExecuteLocalProcedureOK) String() string {
	return fmt.Sprintf("[POST /Custom/Execute][%d] customExecuteLocalProcedureOK  %+v", 200, o.Payload)
}

func (o *CustomExecuteLocalProcedureOK) GetPayload() interface{} {
	return o.Payload
}

func (o *CustomExecuteLocalProcedureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
