// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// DiagnosticsCheckReader is a Reader for the DiagnosticsCheck structure.
type DiagnosticsCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DiagnosticsCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDiagnosticsCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDiagnosticsCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDiagnosticsCheckOK creates a DiagnosticsCheckOK with default headers values
func NewDiagnosticsCheckOK() *DiagnosticsCheckOK {
	return &DiagnosticsCheckOK{}
}

/*
DiagnosticsCheckOK describes a response with status code 200, with default header values.

OK
*/
type DiagnosticsCheckOK struct {
	Payload *models.DatabaseCheckResponse
}

// IsSuccess returns true when this diagnostics check o k response has a 2xx status code
func (o *DiagnosticsCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this diagnostics check o k response has a 3xx status code
func (o *DiagnosticsCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this diagnostics check o k response has a 4xx status code
func (o *DiagnosticsCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this diagnostics check o k response has a 5xx status code
func (o *DiagnosticsCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this diagnostics check o k response a status code equal to that given
func (o *DiagnosticsCheckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the diagnostics check o k response
func (o *DiagnosticsCheckOK) Code() int {
	return 200
}

func (o *DiagnosticsCheckOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /Diagnostics/Check][%d] diagnosticsCheckOK %s", 200, payload)
}

func (o *DiagnosticsCheckOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /Diagnostics/Check][%d] diagnosticsCheckOK %s", 200, payload)
}

func (o *DiagnosticsCheckOK) GetPayload() *models.DatabaseCheckResponse {
	return o.Payload
}

func (o *DiagnosticsCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DatabaseCheckResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDiagnosticsCheckDefault creates a DiagnosticsCheckDefault with default headers values
func NewDiagnosticsCheckDefault(code int) *DiagnosticsCheckDefault {
	return &DiagnosticsCheckDefault{
		_statusCode: code,
	}
}

/*
DiagnosticsCheckDefault describes a response with status code -1, with default header values.

Error
*/
type DiagnosticsCheckDefault struct {
	_statusCode int

	Payload *models.ErrorMessage
}

// IsSuccess returns true when this diagnostics check default response has a 2xx status code
func (o *DiagnosticsCheckDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this diagnostics check default response has a 3xx status code
func (o *DiagnosticsCheckDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this diagnostics check default response has a 4xx status code
func (o *DiagnosticsCheckDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this diagnostics check default response has a 5xx status code
func (o *DiagnosticsCheckDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this diagnostics check default response a status code equal to that given
func (o *DiagnosticsCheckDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the diagnostics check default response
func (o *DiagnosticsCheckDefault) Code() int {
	return o._statusCode
}

func (o *DiagnosticsCheckDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /Diagnostics/Check][%d] Diagnostics_Check default %s", o._statusCode, payload)
}

func (o *DiagnosticsCheckDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /Diagnostics/Check][%d] Diagnostics_Check default %s", o._statusCode, payload)
}

func (o *DiagnosticsCheckDefault) GetPayload() *models.ErrorMessage {
	return o.Payload
}

func (o *DiagnosticsCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorMessage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
