// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// NewPerformancesSearchParams creates a new PerformancesSearchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPerformancesSearchParams() *PerformancesSearchParams {
	return &PerformancesSearchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPerformancesSearchParamsWithTimeout creates a new PerformancesSearchParams object
// with the ability to set a timeout on a request.
func NewPerformancesSearchParamsWithTimeout(timeout time.Duration) *PerformancesSearchParams {
	return &PerformancesSearchParams{
		timeout: timeout,
	}
}

// NewPerformancesSearchParamsWithContext creates a new PerformancesSearchParams object
// with the ability to set a context for a request.
func NewPerformancesSearchParamsWithContext(ctx context.Context) *PerformancesSearchParams {
	return &PerformancesSearchParams{
		Context: ctx,
	}
}

// NewPerformancesSearchParamsWithHTTPClient creates a new PerformancesSearchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPerformancesSearchParamsWithHTTPClient(client *http.Client) *PerformancesSearchParams {
	return &PerformancesSearchParams{
		HTTPClient: client,
	}
}

/*
PerformancesSearchParams contains all the parameters to send to the API endpoint

	for the performances search operation.

	Typically these are written to a http.Request.
*/
type PerformancesSearchParams struct {

	// Request.
	Request *models.PerformanceSearchRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the performances search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformancesSearchParams) WithDefaults() *PerformancesSearchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the performances search params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PerformancesSearchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the performances search params
func (o *PerformancesSearchParams) WithTimeout(timeout time.Duration) *PerformancesSearchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the performances search params
func (o *PerformancesSearchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the performances search params
func (o *PerformancesSearchParams) WithContext(ctx context.Context) *PerformancesSearchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the performances search params
func (o *PerformancesSearchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the performances search params
func (o *PerformancesSearchParams) WithHTTPClient(client *http.Client) *PerformancesSearchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the performances search params
func (o *PerformancesSearchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the performances search params
func (o *PerformancesSearchParams) WithRequest(request *models.PerformanceSearchRequest) *PerformancesSearchParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the performances search params
func (o *PerformancesSearchParams) SetRequest(request *models.PerformanceSearchRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PerformancesSearchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
