// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ServiceResourceUserGroupsCreateReader is a Reader for the ServiceResourceUserGroupsCreate structure.
type ServiceResourceUserGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceResourceUserGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceResourceUserGroupsCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /ReferenceData/ServiceResourceUserGroups] ServiceResourceUserGroups_Create", response, response.Code())
	}
}

// NewServiceResourceUserGroupsCreateOK creates a ServiceResourceUserGroupsCreateOK with default headers values
func NewServiceResourceUserGroupsCreateOK() *ServiceResourceUserGroupsCreateOK {
	return &ServiceResourceUserGroupsCreateOK{}
}

/*
ServiceResourceUserGroupsCreateOK describes a response with status code 200, with default header values.

OK
*/
type ServiceResourceUserGroupsCreateOK struct {
	Payload *models.ServiceResourceUserGroup
}

// IsSuccess returns true when this service resource user groups create o k response has a 2xx status code
func (o *ServiceResourceUserGroupsCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service resource user groups create o k response has a 3xx status code
func (o *ServiceResourceUserGroupsCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service resource user groups create o k response has a 4xx status code
func (o *ServiceResourceUserGroupsCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service resource user groups create o k response has a 5xx status code
func (o *ServiceResourceUserGroupsCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service resource user groups create o k response a status code equal to that given
func (o *ServiceResourceUserGroupsCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service resource user groups create o k response
func (o *ServiceResourceUserGroupsCreateOK) Code() int {
	return 200
}

func (o *ServiceResourceUserGroupsCreateOK) Error() string {
	return fmt.Sprintf("[POST /ReferenceData/ServiceResourceUserGroups][%d] serviceResourceUserGroupsCreateOK  %+v", 200, o.Payload)
}

func (o *ServiceResourceUserGroupsCreateOK) String() string {
	return fmt.Sprintf("[POST /ReferenceData/ServiceResourceUserGroups][%d] serviceResourceUserGroupsCreateOK  %+v", 200, o.Payload)
}

func (o *ServiceResourceUserGroupsCreateOK) GetPayload() *models.ServiceResourceUserGroup {
	return o.Payload
}

func (o *ServiceResourceUserGroupsCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceResourceUserGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
