// Code generated by go-swagger; DO NOT EDIT.

package p_o_s_t

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/skysyzygy/tq/models"
)

// ZoneGroupsCreateReader is a Reader for the ZoneGroupsCreate structure.
type ZoneGroupsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ZoneGroupsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewZoneGroupsCreateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /ReferenceData/ZoneGroups] ZoneGroups_Create", response, response.Code())
	}
}

// NewZoneGroupsCreateOK creates a ZoneGroupsCreateOK with default headers values
func NewZoneGroupsCreateOK() *ZoneGroupsCreateOK {
	return &ZoneGroupsCreateOK{}
}

/*
ZoneGroupsCreateOK describes a response with status code 200, with default header values.

OK
*/
type ZoneGroupsCreateOK struct {
	Payload *models.ZoneGroup
}

// IsSuccess returns true when this zone groups create o k response has a 2xx status code
func (o *ZoneGroupsCreateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this zone groups create o k response has a 3xx status code
func (o *ZoneGroupsCreateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this zone groups create o k response has a 4xx status code
func (o *ZoneGroupsCreateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this zone groups create o k response has a 5xx status code
func (o *ZoneGroupsCreateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this zone groups create o k response a status code equal to that given
func (o *ZoneGroupsCreateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the zone groups create o k response
func (o *ZoneGroupsCreateOK) Code() int {
	return 200
}

func (o *ZoneGroupsCreateOK) Error() string {
	return fmt.Sprintf("[POST /ReferenceData/ZoneGroups][%d] zoneGroupsCreateOK  %+v", 200, o.Payload)
}

func (o *ZoneGroupsCreateOK) String() string {
	return fmt.Sprintf("[POST /ReferenceData/ZoneGroups][%d] zoneGroupsCreateOK  %+v", 200, o.Payload)
}

func (o *ZoneGroupsCreateOK) GetPayload() *models.ZoneGroup {
	return o.Payload
}

func (o *ZoneGroupsCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ZoneGroup)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
