// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LocalProcedureRequest local procedure request
//
// swagger:model LocalProcedureRequest
type LocalProcedureRequest struct {

	// parameter values
	ParameterValues []*ParameterValue `json:"ParameterValues"`

	// parameters
	Parameters string `json:"Parameters,omitempty"`

	// procedure Id
	ProcedureID int32 `json:"ProcedureId,omitempty"`

	// procedure name
	ProcedureName string `json:"ProcedureName,omitempty"`
}

// Validate validates this local procedure request
func (m *LocalProcedureRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateParameterValues(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LocalProcedureRequest) validateParameterValues(formats strfmt.Registry) error {
	if swag.IsZero(m.ParameterValues) { // not required
		return nil
	}

	for i := 0; i < len(m.ParameterValues); i++ {
		if swag.IsZero(m.ParameterValues[i]) { // not required
			continue
		}

		if m.ParameterValues[i] != nil {
			if err := m.ParameterValues[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ParameterValues" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ParameterValues" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this local procedure request based on the context it is used
func (m *LocalProcedureRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateParameterValues(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LocalProcedureRequest) contextValidateParameterValues(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ParameterValues); i++ {

		if m.ParameterValues[i] != nil {

			if swag.IsZero(m.ParameterValues[i]) { // not required
				return nil
			}

			if err := m.ParameterValues[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ParameterValues" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ParameterValues" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *LocalProcedureRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LocalProcedureRequest) UnmarshalBinary(b []byte) error {
	var res LocalProcedureRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
