// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RelationshipCategorySummary relationship category summary
//
// swagger:model RelationshipCategorySummary
type RelationshipCategorySummary struct {

	// description
	Description string `json:"Description,omitempty"`

	// Id
	ID int32 `json:"Id,omitempty"`

	// inactive
	Inactive bool `json:"Inactive,omitempty"`
}

// Validate validates this relationship category summary
func (m *RelationshipCategorySummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this relationship category summary based on context it is used
func (m *RelationshipCategorySummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RelationshipCategorySummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RelationshipCategorySummary) UnmarshalBinary(b []byte) error {
	var res RelationshipCategorySummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
