// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SuperPackageError super package error
//
// swagger:model SuperPackageError
type SuperPackageError struct {

	// error
	Error string `json:"Error,omitempty"`

	// super package line item Id
	SuperPackageLineItemID int32 `json:"SuperPackageLineItemId,omitempty"`
}

// Validate validates this super package error
func (m *SuperPackageError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this super package error based on context it is used
func (m *SuperPackageError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SuperPackageError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SuperPackageError) UnmarshalBinary(b []byte) error {
	var res SuperPackageError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
